Чешев Андрей, Политех, Задание 2
polis-vk/2023-nosql-lsm pull request #100
Opened 2023-10-03 22:44 UTC by Queenore

2023-10-08 19:52 UTC, Marashov-Alexander requested changes
Пока что 8/15. Ход мыслей верный, однако с операцией get есть существенные проблемы:
1) Для чего-то увеличили время поиска элемента в memTable в два раза
2) Лишнее выделение памяти при поиске в ssTable 
До конца среды есть возможность отправить на повторную проверку исправленный вариант. По истечении этого времени мне необходимо будет вмерджить ваш PR в main, поэтому стоит прислать исправления заранее - чтоб у меня было время на проверку

2023-10-08 19:52 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +            this.storagePath = config.basePath().resolve("output.txt");
Строковые и другие константы лучше выносить в настоящие константы с модификаторами private static final String... тогда можно будет дать константам хорошие имена, при необходимости переиспользовать и централизованно менять

2023-10-08 19:52 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +        if (Files.exists(config.basePath())) {
а если не существует, ничего не скажем? Не оговорено в задании конечно, но по-хорошему можно или молча создать эту папку, или исключение бросить (это наверное не желательно), или еще что

2023-10-08 19:52 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +                MemorySegment ssTable = channel.map(
Лайк за очистку арены, однако нужно ли каждый раз создавать арену, создавать мапинг файла в память (который кстати не изменяется)... Может сделать это один раз и потом к нему обращаться?

2023-10-08 19:52 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +                while (ssTable.byteSize() > offset) {
Читабельность будет чуть выше, если перевернуть условие: while offset < ssTable.byteSize(). Мб дело вкуса, но мы же читаем слева направа и потому понятнее видеть слева изменяющуюся переменную, а справа - то, что не меняется

2023-10-08 19:52 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +                return null;
В принципе, после выхода уже есть return null, а тут можно хотя бы в логи вывести ошибку e.printStackTrace

2023-10-08 19:52 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +                                  MemorySegment value,
форматирование чуть поехало

2023-10-08 20:43 UTC, Queenore commented
Хорошо, обязательно исправлю.

2023-10-10 16:45 UTC, Queenore commented
После обновления IDEA возникли проблемы с gradle и java, которые не могу пофиксить уже 2-й день. Сегодня надеюсь получится решить проблему.
p.s. замечания исправил, не могу запустить локально.

2023-10-10 21:53 UTC, Queenore commented
Исправил.

2023-10-11 20:37 UTC, Marashov-Alexander approved these changes
9/15
Из важных замечаний:
1) Открытие одного и того же файла при каждом get. -5 баллов
2) Создание новой арены при закрытии хранилища. -1 балл

2023-10-11 20:37 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +        try (FileChannel channel = FileChannel.open(
Открытие одного и того же файла при каждом get и последующий мапинг - это не круто) Достаточно сделать это один раз и не тратить на то память/время

2023-10-11 20:37 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +                Arena closeArena = Arena.ofConfined()
а для чего здесь создается новая арена? Можно ведь использовать старую - всё равно у них время жизни одинаковое

2023-10-11 20:37 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +                offset = storeAndGetOffset(ssTable, entry.key(), offset);
мб storeAndGetNewOffset тогда? Кажется так будет чуть понятнее происходящее)

2023-10-11 20:37 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/cheshevandrey/InMemoryDao.java
> +            this::compare
похоже больше нет смысла держать метод compare как приватный метод объекта класса (в самом объекте класса не используется, а для мапы будет достаточно static метода или отдельного класса)

2023-10-12 08:24 UTC, merged

2023-10-25 12:53 UTC, Queenore commented
Подскажите, пожалуйста, не могли бы вы повысить балл после исправления за первую домашнюю работу? Преподаватель сказал, что можно попросить проверяющего второе дз посмотреть. Написал сначала в телеграмме, но спустя 20 дней ответа так и не поступило...
![Screenshot_2023-10-25-15-48-49-296_com.github.android.jpg](https://github.com/polis-vk/2023-nosql-lsm/assets/70713475/c3419841-7095-4e9b-a797-91144ecbef02)

2023-10-25 12:54 UTC, Queenore commented
@Marashov-Alexander

2023-10-26 16:15 UTC, Queenore commented
Преподаватель, проверяющий первое дз только что посмотрел.

2023-10-26 16:42 UTC, Queenore commented
Преподаватель, проверяющий 1 дз уже посмотрел.