HW2
polis-vk/2023-nosql-lsm pull request #107
Opened 2023-10-04 10:04 UTC by PetyaVasya

Игорь Ковалев
ИТМО ФИТИП

2023-10-15 20:20 UTC, ikriushenkov requested changes
Поправить `Arena.ofAuto` и другие замечания. Пока 12/15

2023-10-15 20:20 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/kovalevigor/DaoImpl.java
> +            return ssTable.get(key, Arena.ofAuto());
Использование `Arena.ofAuto` не гарантирует, когда будут очищены ресурсы. Кажется, в этом случае мы можем делать это более точно

2023-10-15 20:20 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/kovalevigor/MemoryEntryWriter.java
> +    public static long getTotalMapSize(final Map<MemorySegment, Entry<MemorySegment>> map) {
Странно видеть этот метод в `MemoryEntryWriter`. Тот же`MemoryEntryFileWorker` подходит ему больше

2023-10-15 20:20 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/kovalevigor/SSTable.java
> +    public static final Comparator<MemorySegment> COMPARATOR = UtilsMemorySegment::compare;
Кажется, он может быть `private`

2023-10-15 20:20 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/kovalevigor/SSTable.java
> +                if (UtilsMemorySegment.compare(key, entry.key()) == 0) {
`compare` здесь излишен, так как делает лишние действия. Достаточно сравнить на равенство

2023-10-16 17:08 UTC, PetyaVasya commented on src/main/java/ru/vk/itmo/kovalevigor/DaoImpl.java
> +        memoryArena = Arena.ofShared();
А можете, пожалуйста, подсказать в каком месте? Потому что я не совсем понимаю, что требуется исправить
Просто в таком случае можно убрать `ConcurrentSkipListMap`, чтобы не тратить время на взятие lock'ов, и это ускорит мою программу.

2023-10-16 17:20 UTC, PetyaVasya commented on src/main/java/ru/vk/itmo/kovalevigor/MemoryEntryFileWorker.java
> +    public final MemorySegment data;
1. Ну, опять же, наверное, пользователь снаружи может захотеть узнать, что за `MemorySegment` лежит во Writer'е. Т.к., к сожалению, это структура изменяемая, ссылается неведомо куда и мне никак не ограничить пользователя в его желании что-то записать без моего об этом ведома, то я не увидел никакого смысла делать ее `private` или `protected`. От того, что сейчас данным полем пользуются лишь классы наследники, не отменяет обратного желания в будущем.
Хотя, возможно, мы создали `MemoryEntryWriter` и куда-то отдали для записи и не хотим, чтобы он мог иметь доступ к `MemorySegment` и в таком случае логично сделать для него getter, где он будет возвращаться в режиме только для чтения

Кажется, замечание было вполне справедливо. Надеюсь, что простыня выше ответила на вопрос "зачем"
2. Не совсем понял, что не так с полем `offset`. Предлагается сделать геттер `public`? 
Вполне вероятно, что стоило сделать отдельный интерфейс `MemoryEntryFileWorker`, т.к. текущая реализация содержит много общего, так и множество конкретики, например, `ENTRY_META_SIZE`. 
В моей реализации, например, вовсе не может быть `offset` и его может заменять какая-то более сложная конструкция. Возможно, мне бы захотелось запретить записывать повторно и я бы накатил какой-то `assert`. 
В общем, не понимаю вопроса и проблемы.

2023-10-16 17:21 UTC, PetyaVasya commented on src/main/java/ru/vk/itmo/kovalevigor/MemoryEntryReader.java
> +            Arena arena
Точно не уверен, но кажется на это жалуется чекер стилей, потому что я лепил `final` везде. Проверю еще раз

2023-10-17 19:51 UTC, PetyaVasya commented on src/main/java/ru/vk/itmo/kovalevigor/MemoryEntryReader.java
> +            Arena arena
Оказывается, это просто в try не нужно ставить final

2023-10-18 21:38 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/kovalevigor/SSTable.java
> +    public static final Comparator<MemorySegment> COMPARATOR = UtilsMemorySegment::compare;
Решение спорное, но ок, принимается

2023-10-18 21:40 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/kovalevigor/MemoryEntryFileWorker.java
> +    public final MemorySegment data;
2. Странно видеть протектед геттер с приватным полем. Кажется, более логичным было бы просто протектед поле

2023-10-18 21:41 UTC, ikriushenkov approved these changes
Мелкие замечания 14/15

2023-10-22 17:51 UTC, merged