Тузиков Александр, Магистратура ИТМО "Распределенные веб-сервисы", 2 лабораторная
polis-vk/2023-nosql-lsm pull request #108
Opened 2023-10-04 11:00 UTC by alexBlack01

2023-10-04 19:39 UTC, alexBlack01 commented
Поправил конфликты из ветки первой лабы и исправил код в соответствии с замечаниями (вроде).

2023-10-05 20:16 UTC, alexBlack01 commented
На момент дедлайна все было норм

2023-10-09 20:37 UTC, atimofeyev requested changes

2023-10-09 20:37 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/tuzikovalexandr/InMemoryDaoImpl.java
>      private final ConcurrentSkipListMap<MemorySegment, Entry<MemorySegment>> memory =
тип поля лучше делать наиболее абстрактным

2023-10-09 20:37 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/tuzikovalexandr/SSTable.java
> +        try (FileChannel fc = FileChannel.open(filePath, StandardOpenOption.READ)) {
слишком дорого открывать файл на каждое чтение

2023-10-09 20:37 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/tuzikovalexandr/SSTable.java
> +            MemorySegment readSegment = fc.map(READ_ONLY, 0, Files.size(filePath), Arena.global());
глобальная арена плохо при использовании глобальной арены сегменты не деаллоцируются, так мы всю память съедим

2023-10-11 19:00 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/tuzikovalexandr/InMemoryDaoImpl.java
>      private final ConcurrentSkipListMap<MemorySegment, Entry<MemorySegment>> memory =
Поправил

2023-10-11 19:00 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/tuzikovalexandr/SSTable.java
> +        try (FileChannel fc = FileChannel.open(filePath, StandardOpenOption.READ)) {
Поправил

2023-10-11 19:00 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/tuzikovalexandr/SSTable.java
> +            MemorySegment readSegment = fc.map(READ_ONLY, 0, Files.size(filePath), Arena.global());
Поправил

2023-10-17 21:04 UTC, atimofeyev requested changes

2023-10-17 21:10 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/tuzikovalexandr/SSTable.java
> +                writeSegment.asSlice(offset).copyFrom(entry.value());
5 баллов

2023-10-17 21:16 UTC, atimofeyev commented
Текущие замечания поправьте пожалуйста уже в след пул реквесте этапа 3, там будут тесты которые не пройдут в текущем решении

2023-10-17 21:22 UTC, merged