ДЗ-2, Солонец Арсений, распределенные веб-сервисы, ИТМО
polis-vk/2023-nosql-lsm pull request #112
Opened 2023-10-04 16:06 UTC by solosenya

2023-10-09 20:22 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/solonetsarseniy/helpers/DataStorageManager.java
> +    private final Arena arena = Arena.global();
сегменты аллоцированные глобальной ареной никогда не деалоцируются?
Так очень легко съесть всю память

2023-10-09 20:27 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/solonetsarseniy/helpers/DataStorageManager.java
> +        try (FileChannel dataChannel = FileChannel.open(path, READ_OPTIONS_KIT)) {
очень неэффективно на каждый гет открывать файл, в том то и дея ммап, чтобы один раз открыть файл и потом по нему бегать

2023-10-11 14:54 UTC, solosenya commented on src/main/java/ru/vk/itmo/solonetsarseniy/helpers/DataStorageManager.java
> +        try (FileChannel dataChannel = FileChannel.open(path, READ_OPTIONS_KIT)) {
открытие вынес

2023-10-11 14:54 UTC, solosenya commented on src/main/java/ru/vk/itmo/solonetsarseniy/helpers/DataStorageManager.java
> +    private final Arena arena = Arena.global();
изменил арену

2023-10-11 14:55 UTC, solosenya commented on src/main/java/ru/vk/itmo/solonetsarseniy/InMemoryDao.java
> +        return databaseContainsKey
исправил на один вызов

2023-10-17 21:03 UTC, atimofeyev requested changes

2023-10-17 21:03 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/solonetsarseniy/helpers/DataStorageManager.java
> +    private final Arena arena = Arena.ofConfined();
Это же не будет работать в многопоточной среде

2023-10-17 21:09 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/solonetsarseniy/helpers/DataStorageManager.java
> +    private final Arena arena = Arena.ofConfined();
5 баллов

2023-10-17 21:10 UTC, atimofeyev approved these changes

2023-10-17 21:16 UTC, atimofeyev commented
Текущие замечания поправьте пожалуйста уже в след пул реквесте этапа 3, там будут тесты которые не пройдут в текущем решении

2023-10-17 21:21 UTC, merged