Корж Владислав, Политех, задание 2
polis-vk/2023-nosql-lsm pull request #113
Opened 2023-10-04 16:29 UTC by sold666

2023-10-18 12:41 UTC, lamtev requested changes
Решение оценивается в 5 баллов из 15. Баллы снимались за мажорные проблемы. Давайте их пофиксим, очень желательно, как можно быстрее, и итоговый балл будет пересчитан

На будущее: неплохо бы идею реализации персистентного хранения пояснить в комментах в классе или в описании пулл реквеста

2023-10-18 12:41 UTC, lamtev commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +        if (dataStore.containsKey(key)) {
[major] Двойной лукап в `NavigableMap`, когда достаточно одиночного

2023-10-18 12:41 UTC, lamtev commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +        long valueSize;
[minor] выглядит так, что скоуп видимости обеих переменных может быть уменьшен путём перемещения внутрь цикла

2023-10-18 12:41 UTC, lamtev commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +            MemorySegment keySegment = dataSegment.asSlice(offset + Long.BYTES, keySize);
[major] Избыточная аллокация, данная переменная не требуется. Выполнить сравнение можно через `static MemorySegment.mismatch()`, а в качестве ключа для `BaseEntry` аргумент функции

2023-10-18 12:41 UTC, lamtev commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +    private final Arena arena = Arena.ofConfined();
На занятии после дедлайна по заданию немного было рассказано про арены. Надеюсь, к текущему моменту есть понимание, насколько хорошо использовать `Arena.ofConfined()`. И в будущих этапах это будет учтено

2023-10-18 12:41 UTC, lamtev commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +        if (dataStore.containsKey(key)) {
К слову, после фикса пропадёт необходимость в `protected` видимости для `dataStore `

2023-10-18 13:22 UTC, sold666 commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +    private final Arena arena = Arena.ofConfined();
Как я понял доступ к сегментам, выделенным с помощью ограниченной арены, может получить только поток, создавший арену. Поэтому такой подход может обеспечить более высокую производительность при использовании многопоточности

2023-10-18 15:05 UTC, lamtev commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +    private final Arena arena = Arena.ofConfined();
> Как я понял доступ к сегментам, выделенным с помощью ограниченной арены, может получить только поток, создавший арену

Что будет при обращении к арене другого потока?

2023-10-18 15:46 UTC, sold666 commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +    private final Arena arena = Arena.ofConfined();
WrongThreadException

2023-10-18 15:47 UTC, sold666 commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +    private final Arena arena = Arena.ofConfined();
> > Как я понял доступ к сегментам, выделенным с помощью ограниченной арены, может получить только поток, создавший арену
> 
> Что будет при обращении к арене другого потока?

WrongThreadException

2023-10-18 17:54 UTC, sold666 commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +    private final Arena arena = Arena.ofConfined();
> Нет противоречия с
> > Поэтому такой подход может обеспечить более высокую производительность при использовании многопоточности
> 
> ?)

Упс, да, не совсем правильно написал... 
Наоборот они поддерживают строгие гарантии ограничения потоков.  При создании им назначается поток- owner, обычно это поток, который инициировал операцию создания.  Доступ к сегментам, созданным ограниченной ареной, возможен только для потока-owner.

2023-10-18 18:22 UTC, lamtev requested changes
Обнаружил еще серьёзные недочёты (отметил их [major]). Прошу прокомментировать и исправить, если требуется

2023-10-18 18:28 UTC, lamtev commented
Поздненько проверил решение. Не призываю бросать допиливание 3 этапа ради фиксов в этом. Лучше успеть до дедлайна 3 этап. И потом пофиксить этот

2023-10-18 20:17 UTC, sold666 commented on src/main/java/ru/vk/itmo/korzhvladislav/PersistentDao.java
> +        try (FileChannel dataChannel = FileChannel.open(dataFilePath, READ)) {
Да, поменял, как было на лекции

2023-10-19 09:32 UTC, lamtev approved these changes
12 баллов

2023-10-19 09:33 UTC, merged