Бандурин Владислав, ИТМО ФИТиП М33321, HW2
polis-vk/2023-nosql-lsm pull request #115
Opened 2023-10-04 16:55 UTC by vbandurin7

2023-10-11 21:17 UTC, AlexeyShik requested changes
Нужно поправить `map` на каждый `get` запрос.

2023-10-11 21:17 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +                    MemorySegment entryKey = fileSegment.asSlice(offset, keySize);
Если не совпали длины ключей, можно не читать сам ключ, соответственно, не делать лишнюю аллокацию. 

То есть какой порядок я предлагаю:
- читаем длину ключа
- если длины ключей не совпали, то continue
- читаем ключ
- если ключи не совпали, то continue
- читаем значение и возвращаем entry

2023-10-11 21:17 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +                    if (MEMORY_SEGMENT_COMPARATOR.compare(key, entryKey) == 0) {
Компаратор все же делает лишние действия, здесь достаточно просто проверить `mismatch` на -1.

2023-10-11 21:17 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +                fileSegmentSize += e.getKey().byteSize() + e.getValue().value().byteSize() + 16;
Вместо 16 лучше явно писать что-то вида `2 * Long.BYTES`, чтобы было проще читать код.

2023-10-12 18:17 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +public class InMemoryDao implements Dao<MemorySegment, Entry<MemorySegment>> {
Поправил

2023-10-12 18:17 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +    private final Arena daoArena = Arena.ofConfined();
Спасибо, учту

2023-10-12 18:19 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +        if (Files.exists(persistentStorage)) {
В первый раз меня смутило, что return null приходится дописывать в начале и в конце, но кажется с вашим вариантом все равно лучше смотрится

2023-10-12 18:20 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +                MemorySegment fileSegment = fileChannel.map(
Обсуждали, что возможно беда с тестами при правильной реализации, отправил в лс изменения на другой ветке

2023-10-12 18:20 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +                    long keySize = fileSegment.get(ValueLayout.JAVA_LONG_UNALIGNED
поправил, почему-то в первый раз казалось, что не взлетит

2023-10-12 18:21 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +                fileSegmentSize += e.getKey().byteSize() + e.getValue().value().byteSize() + 16;
Fixed

2023-10-12 18:21 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +                    if (MEMORY_SEGMENT_COMPARATOR.compare(key, entryKey) == 0) {
Fixed

2023-10-12 20:36 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/bandurinvladislav/InMemoryDao.java
> +                MemorySegment fileSegment = fileChannel.map(
Fixed

2023-10-13 14:35 UTC, AlexeyShik approved these changes
Все хорошо, по баллам чуть позже отпишу.

2023-10-16 16:52 UTC, merged