Солнышко Ксения, M33321, ФИТиП ИТМО, Stage 2
polis-vk/2023-nosql-lsm pull request #118
Opened 2023-10-04 17:26 UTC by persehoney

2023-10-05 11:51 UTC, incubos commented
Почему вы удалили чужие решения?

2023-10-05 15:29 UTC, persehoney commented
> Почему вы удалили чужие решения?

проиграла с гитом. это критично?

2023-10-05 19:31 UTC, incubos commented
Да, в таком виде решение не будем вмёрдживать. Выпилите удаления?

On Thu, Oct 5, 2023, 18:30 ксюша солнышко ***@***.***> wrote:

> Почему вы удалили чужие решения?
>
> проиграла с гитом. это критично?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/polis-vk/2023-nosql-lsm/pull/118#issuecomment-1749138546>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFCRXORMHOBMXKNEYT34EDX53G7ZAVCNFSM6AAAAAA5S7JP7WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBZGEZTQNJUGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-10-12 06:54 UTC, AlexeyShik requested changes
Нужно поправить, чтобы вся sstable не читалась в память. Ожидалось, что вы будете читать её по кускам в `get`, на паре обсуждали.

2023-10-12 06:54 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +        MemorySegment mappedSSTable = mapFileToSegment(storageSize, FileChannel.MapMode.READ_WRITE,
Здесь не хватает одной опции на случай, если файл уже существует и не пустой, например, там хранятся данные с прошлой записи sstable. 

https://stackoverflow.com/questions/62394352/difference-between-standardopenoption-write-standardopenoption-create-with-wit

2023-10-12 06:54 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +    private static final int SIZE_BYTE = Long.BYTES;
Лучше использовать общепринятую константу `Long.BYTES`. И название `SIZE_BYTE` наверное не самое удачное, потому что не дает контекста, что это размер именно лонга.

2023-10-12 06:54 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +    private Path pathToSSTable;
Это норм, но более расширяемым решением было бы сохранить `Config`.

2023-10-12 06:54 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +    private final NavigableMap<MemorySegment, Entry<MemorySegment>> persistentStorage =
Мы же обсуждали на паре, что нельзя читать всю таблицу в память(

2023-10-12 06:54 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +    public void close() throws IOException {
Вот тут еще стоит закрывать арену, чтобы освободить замаппленную память.

2023-10-12 06:54 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +    private final Comparator<MemorySegment> comparator = DaoImpl::compare;
Стоит сделать static

2023-10-12 13:56 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +        arena.close();
А если второй раз вызовут `close` на вашем dao? `arena.close()` ведь не идемпотентная операция, судя по документации.

2023-10-12 13:59 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +    public synchronized void upsert(Entry<MemorySegment> entry) {
Откуда тут появился `synchronized`? Вроде не было в интерфейсе.

2023-10-12 14:01 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +            if (persistentKey.byteSize() == key.byteSize() && compare(key, persistentKey) == 0) {
`compare` все же делает несколько лишних операций, нам ведь важно только сравнить на равенство, то есть достаточно проверить `mismatch` на равенство -1

2023-10-12 14:03 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +            MemorySegment persistentValue = getSegment(mappedSSTable, offset);
Если не совпала длина или сами ключи, лучше не читать само значение.

Если учитывать, что мы читаем все записи подряд и почти все из них не подходят к данному ключу, получается, что будет O(число записей в sstable) лишних аллокаций на get одного ключа.

2023-10-12 14:04 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/solnyshkoksenia/DaoImpl.java
> +            MemorySegment persistentKey = getSegment(mappedSSTable, offset);
Аналогично, в случае, если не совпали длины ключей, можно не читать сам ключ, соответственно, не делать лишнюю аллокацию.

То есть какой порядок я предлагаю:
- читаем длину ключа
- если длины ключей не совпали, то continue
- читаем ключ
- если ключи не совпали, то continue
- читаем значение и возвращаем entry

2023-10-12 14:09 UTC, AlexeyShik approved these changes
Глобальных замечаний нет, по баллам напишу чуть позже.

2023-10-21 23:07 UTC, AlexeyShik approved these changes
8 баллов.
Изначальное решение не подходило под условие дз, чтобы в get был поиск по sstable.

2023-12-11 21:35 UTC, closed without merging