Осипов Даниил ИТМО ФИТиП HW2
polis-vk/2023-nosql-lsm pull request #125
Opened 2023-10-04 19:45 UTC by Sbread

2023-10-18 00:09 UTC, AlexeyShik requested changes
Нужно поправить `map` на каждый get. В остальном классное решение.

2023-10-18 00:09 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +                if (memSegmentComparator.compare(key, expectedKey) == 0) {
Здесь лучше сравнить `mismatch` на равенство -1 , потому что компаратор делает дополнительные лишние действия

2023-10-18 00:09 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +                    FileChannel.MapMode.READ_ONLY, 0, ssTableFileSize, Arena.ofShared());
Почему тут арена ofShared, а в close ofConfined?

2023-10-18 00:09 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +            final MemorySegment mappedMemorySegment = fileChannel.map(
Лучше сделать `map` один раз в конструкторе и затем работать с этим MemorySegment. Так как у нас sstable иммутабельный, то это лишний действия.

2023-10-19 19:48 UTC, Sbread commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +                    FileChannel.MapMode.READ_ONLY, 0, ssTableFileSize, Arena.ofShared());
В close мы перезаписываем файл, нам там доступ множества потоков не нужен

2023-10-19 19:48 UTC, Sbread commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +            final MemorySegment mappedMemorySegment = fileChannel.map(
fixed

2023-10-19 19:48 UTC, Sbread commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +                if (memSegmentComparator.compare(key, expectedKey) == 0) {
fixed

2023-10-21 22:08 UTC, AlexeyShik approved these changes
14 баллов

2023-10-21 22:08 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +                    FileChannel.MapMode.READ_ONLY, 0, ssTableFileSize, Arena.ofShared());
`Arena.ofShared` explicitly closable, получается, что MemorySegment так и останется замапленным.

2023-10-21 22:08 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +                    FileChannel.MapMode.READ_ONLY, 0, ssTableFileSize, Arena.ofShared());
Правильная идея, тем не менее пока вы никак не гарантируете, что закрытием dao будет заниматься только один поток. Теоретически могут быть как конкурентные вызовы close/close, так и close/get, и в обоих случаях что-то может пойти не так. В этом стейдже не требуется 100% корректная многопоточка, но на будущее.

2023-10-30 23:32 UTC, Sbread commented on src/main/java/ru/vk/itmo/osipovdaniil/InMemoryDao.java
> +                    FileChannel.MapMode.READ_ONLY, 0, ssTableFileSize, Arena.ofShared());
Закрыл арену

2023-10-30 23:32 UTC, Sbread commented
> 14 баллов И нужно поправить codeclimate

поправил

2023-11-06 10:22 UTC, merged