HW-2, Белоногов Николай, СПБПУ.
polis-vk/2023-nosql-lsm pull request #126
Opened 2023-10-04 19:58 UTC by nickkkcc

2023-10-08 18:08 UTC, Marashov-Alexander requested changes
Пока 3/15 из-за лишних выделений памяти, отсутствия управления памятью через арены, лишние операции. Есть возможность поправить до конца среды, чтоб я проверил еще раз. Только надо помнить, что к этому времени я уже должен буду вмерджить этот PR, поэтому лучше прислать чуть заранее и оставить мне время на проверку :)

2023-10-08 18:08 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        readingPreparation();
а для чего каждый раз мапить память на файл? Может дешевле будет один раз замаппить и не создавать лишних объектов после?

2023-10-08 18:08 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        while (index < (this.fileSizes[1] - Long.BYTES) / 8 - 1) {
а правый аргумент меняется после итерации цикла? Кажется, что нет - и лучше закэшировать значение. Так и название можно дать переменной понятное, и лишних вычислений не будет

2023-10-09 16:58 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
>      private final NavigableMap<MemorySegment, Entry<MemorySegment>> arena;
Из тех же соображений, из которых разработчики MemorySegment назвали свою арену - это устоявшееся наименование  "пространства хранения".

2023-10-09 16:58 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
> +            } catch (IOException e) { // will be using with logging.
Настройка Sonar не позволяет использовать этот вариант.

2023-10-09 16:59 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +            Entry<MemorySegment>> entries) throws IOException, PathNotFoundException {
Мисклик видать)

2023-10-09 16:59 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        long fileSize = entries.values().stream()
Хорошее замечание!

2023-10-09 17:00 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +    public NavigableMap<MemorySegment, Entry<MemorySegment>> readEntries() throws IOException {
Описал проблему в комменте о комментах)

2023-10-09 17:01 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +    private MemorySegment map(Path filePath, long byteSize, FileChannel.MapMode mode,
Для варианта ЧТЕНИЯ-ЗАПИСЬ и ТОЛЬКО-ДЛЯ-ЧТЕНИЯ?

2023-10-09 17:02 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/exceptions/package-info.java
> + * Contains classes of exceptions when working with {@link ru.vk.itmo.Dao Dao}.
Привычка, у нас почему-то требуют.

2023-10-09 17:07 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +            Entry<MemorySegment>> entries) throws IOException, PathNotFoundException {
Недорефакторил.

2023-10-09 17:18 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
>      public Iterator<Entry<MemorySegment>> allFrom(MemorySegment from) {
Не знаю, мне кажется странно использовать более общий класс решений в более частных, нежели использовать более частные решения в общем.

2023-10-10 07:20 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
>      private final NavigableMap<MemorySegment, Entry<MemorySegment>> arena;
В java понятие арена ассоциируется с классом Arena, у которого смысл в управлении жизненным циклом памяти, выделенной в скоупе этой арены. У объекта типа map смысл совершенно другой. Мапа не управляет памятью - это лишь хранилище, которая может запрашивать память под свои нужды. Исходя из вышеизложенного, название для мапы "арена" конфликтует с понятием арены в java и тем самым путает читающего

2023-10-10 07:23 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
>      public Iterator<Entry<MemorySegment>> allFrom(MemorySegment from) {
Твой вариант имеет право на существование, в нем есть свои плюсы. Тут дело скорее в том, что изначально на уровне архитектуры был выбран один вариант, а в наследнике переделано на обратный. Баллы снижать не буду в любом случае, но осуждаю)

2023-10-10 07:24 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
> +            } catch (IOException e) { // will be using with logging.
Понял. Тогда снимаю вопрос

2023-10-10 07:27 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/belonogovnikolay/exceptions/package-info.java
> + * Contains classes of exceptions when working with {@link ru.vk.itmo.Dao Dao}.
В больших и сложных проектах эта практика была бы неплохой. Может есть смысл приучать себя вести документацию. Хз, что бы сказали остальные ревьюверы, но лично я не против

2023-10-10 08:38 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
> +    public static Dao<MemorySegment, Entry<MemorySegment>> newInstance(Config config) {
Мне кажется, что это повышает читаемость и понимание того, что делает этот метод. Конструкторы могут представлять из себя что-то непонятное внутри +  доп. слово `new`. `newInstance(...)` -  хорошее название для обозначения того, что этот метод каждый раз возвращает новый экземпляр класса.

2023-10-10 14:47 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
> +    public static Dao<MemorySegment, Entry<MemorySegment>> newInstance(Config config) {
А конструктор разве не призван каждый раз возвращать новый экземпляр класса? :)

Ну это мое личное мнение, баллы за это в любом случае не снимаются. Up to you

2023-10-11 09:56 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/FileType.java
> +    private final String name;
Поправил.

2023-10-11 10:01 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
>      private final NavigableMap<MemorySegment, Entry<MemorySegment>> arena;
Исправлено.

2023-10-11 10:07 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
> +        //this.arena = persistenceHelper.readEntries(); commented in PR too.
Исправлено.

2023-10-11 10:11 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/InMemoryTreeDao.java
> +        if (Objects.isNull(entry)) {
Исправил.

2023-10-11 10:14 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +            Entry<MemorySegment>> entries) throws IOException, PathNotFoundException {
Исправил.

2023-10-11 10:15 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +            Entry<MemorySegment>> entries) throws IOException, PathNotFoundException {
Исправил.

2023-10-11 10:29 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        long fileSize = entries.values().stream()
Исправил.

2023-10-11 10:39 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +    private final Path[] pathsToFile;
Исправил.

2023-10-11 10:49 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        while (index < (this.fileSizes[1] - Long.BYTES) / 8 - 1) {
Исправил.

2023-10-11 10:55 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        MemorySegmentComparator segmentComparator = new MemorySegmentComparator();
Исправлено.

2023-10-11 10:56 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        while (index < (this.fileSizes[1] - Long.BYTES) / 8 - 1) {
Исправлено. Через кэширование переменной.

2023-10-11 11:08 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +    private MemorySegment map(Path filePath, long byteSize, FileChannel.MapMode mode,
Исправил.

2023-10-11 11:11 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +            throw new PathNotFoundException("The directory to the "
Исправил.

2023-10-11 11:20 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        readingPreparation();
Исправил.

2023-10-11 13:44 UTC, nickkkcc commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +            throw new PathNotFoundException("The directory to the "
Настройки sonar не позволяют выбрасывать NullPointerException. Предлагаю считать, что конфиг не может быть null. В любом случае мы поулчим исключение, если передадут null.

2023-10-11 20:37 UTC, Marashov-Alexander approved these changes
9/15
Из важных замечаний:
1) Создается множество арен, в то время как достаточно одной. -1 балл
2) При каждом get проверяется наличие файлов и выделение памяти через asSlice. -5 баллов

2023-10-11 20:37 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/belonogovnikolay/PersistenceHelper.java
> +        positionOffsets = new long[size * 2 + 1];
Тут тоже со стороны если смотреть, то не оч очевидно, почему 2 и почему плюс 1. Возможно есть смысл как-то это пояснить

2023-10-12 10:04 UTC, merged