Кононов Владимир ФИТиП Итмо бакалавр 2 дз
polis-vk/2023-nosql-lsm pull request #127
Opened 2023-10-04 19:59 UTC by lukna5

Добавлено 2 дз

2023-10-04 21:04 UTC, lukna5 commented
I don't known why, но почему-то у меня  тестируются чужие репозитории и мне это не нравится и приходится удалять чужой код

2023-10-05 11:52 UTC, incubos commented
Почему вы удалили чужие решения?

2023-10-06 06:46 UTC, lukna5 commented
> Почему вы удалили чужие решения?
У меня была бага, из-за которой у меня тестировались все репозитории и соответственно падало все,
мне в вк ответили, что бага была в том, что я менял stage не там. Исправил это.

2023-10-09 00:30 UTC, ikriushenkov requested changes
Нужно исправить. Пока 7/19

2023-10-09 00:30 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +                StandardOpenOption.WRITE, StandardOpenOption.CREATE, StandardOpenOption.CREATE)) {
Лишний `StandardOpenOption.CREATE`

2023-10-09 00:30 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +                            dataWriteSegment.asSlice(offsetData, value.value().byteSize()).copyFrom(value.value());
Лишняя аллокация в `asSlice`. Можно без нее

2023-10-09 00:30 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +    public void close() throws IOException {
Не удаляется файл в `close`

2023-10-09 00:30 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            dataSegment = fileChanel.map(FileChannel.MapMode.READ_ONLY, 0, fileChanel.size(), Arena.ofConfined());
`Confined` - Explicitly closeable. Ее в `close()` нужно явно закрывать

2023-10-09 00:30 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            Files.deleteIfExists(dataPath);
На каждый вызов `get` мы проверяем, что файл существует

2023-10-09 00:30 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            if (memorySegmentComparator.compare(keySegmentSlice, key) == 0) {
В `compare` происходят лишние действия

2023-10-09 10:29 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/FactoryImpl.java
> +    }
Исправил

2023-10-09 11:43 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            Files.deleteIfExists(dataPath);
Исправил

2023-10-09 11:45 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +    public void close() throws IOException {
Исправил

2023-10-09 11:47 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            keySegment = null;
Исправил

2023-10-09 11:47 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +                StandardOpenOption.WRITE, StandardOpenOption.CREATE, StandardOpenOption.CREATE)) {
Исправил

2023-10-09 11:47 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +    private MemorySegment keySegment;
Исправил

2023-10-09 11:50 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            if (memorySegmentComparator.compare(keySegmentSlice, key) == 0) {
Не понимаю какие, если сравнивать на равно ==, то будет некорректно (так как 2 разных объекта), здесь вроде как у меня оптимальный компаратор, который через missmatch (оптимальный метод поиска различий) находит разницу

2023-10-09 11:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            if (memorySegmentComparator.compare(keySegmentSlice, key) == 0) {
`mismatch` действительно оптимальный метод, но в компараторе вы возвращаете 0 только когда `mismatch ` возвращает -1. Непонятно зачем сравнивать `MemorySegment` на больше/меньше, когда вам нужно только узнать равны ли они, что можно сделать только через `mismatch`

2023-10-09 12:02 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            if (memorySegmentComparator.compare(keySegmentSlice, key) == 0) {
Так остальные операции за O(1) же (и без захода в файловую систему), или это тоже нужно минимизировать?

2023-10-09 12:02 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            if (memorySegmentComparator.compare(keySegmentSlice, key) == 0) {
Как будто с точки зрения понятности кода, так легче понять что происходит в ифе

2023-10-09 12:04 UTC, lukna5 commented
Правки пока что предварительные и не рабочие

2023-10-09 12:10 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            if (memorySegmentComparator.compare(keySegmentSlice, key) == 0) {
Есть вызовы `get` у `MemorySegment` и `byteSize`, точные реализации которых мы не знаем, и которые в том числе могут ходить куда-то, так как `MemorySegment` лишь интерфейс, но которые точно не нужны для проверки их на равенство. Если вам кажется, что отдельная функция увеличит понятность, то лучше создать отдельную функцию, которая будет сравнивать и не делать лишних действий

2023-10-10 21:51 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +                            dataWriteSegment.asSlice(offsetData, value.value().byteSize()).copyFrom(value.value());
Исправил

2023-10-10 21:52 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            dataSegment = fileChanel.map(FileChannel.MapMode.READ_ONLY, 0, fileChanel.size(), Arena.ofConfined());
Исправил

2023-10-10 21:52 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +            if (memorySegmentComparator.compare(keySegmentSlice, key) == 0) {
Исправил

2023-10-11 13:45 UTC, ikriushenkov approved these changes
Вторая проверка. 9/15

2023-10-11 16:25 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +                            }
Не особо понял в чем плох данный метод, потому что у них какой более эффективный способ получения (get сразу всего участка памяти?). Также не уверен, что правильно понял проблему asSlice (потому что он выделит память при asSlice и при copy еще раз выделит?) Исправил

2023-10-11 16:25 UTC, lukna5 commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +        if (dataPath == null || keyPath == null) {
Исправил

2023-10-11 18:59 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/test/kononovvladimir/InMemoryDao.java
> +                            }
В `asSlice` вы создаете лишний временный объект, без которого можно обойтись. Здесь же вы копируете память по одному байтику, когда это можно делать гораздо более эффективно (как вы это сделали сейчас)

2023-10-11 18:59 UTC, merged