HW2 Селецкая Алиса, Политех
polis-vk/2023-nosql-lsm pull request #131
Opened 2023-10-04 20:23 UTC by sealisaa

2023-10-12 10:52 UTC, incubos commented
Не проходит проверка на `LineLength`.
Падает тест:
```
PersistentTest > differentKeyValues(Dao) > [2] TestDao<seletskayaalisa.InMemoryDao> FAILED
    java.lang.IndexOutOfBoundsException at PersistentTest.java:140
```

2023-10-18 14:30 UTC, lamtev requested changes
На текущий момент тесты красные, и очень вероятно, что из-за бага в реализации этапа

Мне показалось, что к дедлайну тесты были зелёными, то есть формальности соблюдены были, поэтому решение проверялось. Если я ошибся, прошу поправить.

Оценка пока 0 баллов из-за мажорных проблем + красного теста. Чтобы итоговый балл был пересчитан, необходимо это исправить

2023-10-18 14:30 UTC, lamtev commented on src/main/java/ru/vk/itmo/seletskayaalisa/InMemoryDao.java
> +            return fileChannel.map(mode, 0, byteSize, Arena.ofConfined());
[major] Новая арена на каждый get из файла, когда арены достаточно одной

2023-10-19 11:07 UTC, lamtev commented
@sealisaa прошу ответить. и, если требуется, поскорее внести правки, и получить оценку

2023-10-29 10:45 UTC, lamtev commented
0 баллов :(

2023-10-29 10:45 UTC, closed without merging