ДЗ-2 Грунский Алексей ИТМО ФиТИП
polis-vk/2023-nosql-lsm pull request #133
Opened 2023-10-04 20:47 UTC by MegaVerkruzo

2023-10-17 23:36 UTC, AlexeyShik requested changes
Нужно поправить, чтобы в get был поиск по sstable. 
С файлом стоит работать через java.nio.channels.FileChannel#map(java.nio.channels.FileChannel.MapMode, long, long, java.lang.foreign.Arena), он как раз дает MemorySegment. Но тут нужно аккуратно выбрать опции и арену.

2023-10-17 23:36 UTC, AlexeyShik commented on build.gradle
> -    maxHeapSize = "64m"
Не, тесты менять нельзя, надо откатить и заново пройти тесты

2023-10-17 23:36 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/grunskiialexey/MemorySegmentDao.java
> +                    Arrays.compare(o1.toArray(ValueLayout.JAVA_BYTE), o2.toArray(ValueLayout.JAVA_BYTE))
`toArray` делает java.lang.foreign.MemorySegment#copy, то есть не просто создает ссылку, а перекопирует все байты. Такое нельзя делать в компараторе. Лучше всего сделать через `mismatch`, тогда даже лишей ссылки не будет аллоцироваться

2023-10-17 23:36 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/grunskiialexey/MemorySegmentDao.java
> +            Files.delete(filePath);
Лучше работать с файлом через `FileChannel`, тогда достаточно будет передать нужные опции и не придется удалять/создавать файл

2023-10-17 23:36 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/grunskiialexey/MemorySegmentDao.java
> +                outputStream.write(ByteBuffer.allocate(4).putInt(key.length).array());
Много промежуточных аллокаций на `.allocate`. Можно сделать лучше, выделив в самом начале метода MemorySegment методом java.nio.channels.FileChannel#map(java.nio.channels.FileChannel.MapMode, long, long, java.lang.foreign.Arena) ровно необходимое число байт.

2023-10-17 23:36 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/grunskiialexey/MemorySegmentDaoFactory.java
> +    public Dao<MemorySegment, Entry<MemorySegment>> createDao(Config config) throws IOException {
Предлагаю содержательную логику вынести из этого класса. Все же он вспомогательный чисто для тестов.

2023-10-17 23:36 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/grunskiialexey/MemorySegmentDaoFactory.java
> +            List<Entry<MemorySegment>> list = new ArrayList<>();
Суть задания была в том, чтобы в get обходить sstable, а не считывать его в память. На паре обсуждали(

2023-10-17 23:36 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/grunskiialexey/MemorySegmentDaoFactory.java
> +        return new BaseEntry<>(
А зачем тут копировать?

2023-10-18 07:18 UTC, MegaVerkruzo commented on src/main/java/ru/vk/itmo/test/grunskiialexey/MemorySegmentDaoFactory.java
> +        return new BaseEntry<>(
(возможно, какие-то изменения я еще не запушил, но как локально все поправлю, тогда и сделаю request на review)

2023-10-18 07:20 UTC, MegaVerkruzo commented on src/main/java/ru/vk/itmo/test/grunskiialexey/MemorySegmentDaoFactory.java
> +            List<Entry<MemorySegment>> list = new ArrayList<>();
Всё так, неверно понял формулировку:(

2023-10-18 18:23 UTC, MegaVerkruzo commented
Пыр исправил, переписав всю логику на FileChannel, так уже гораздо лучше и красивее, но если есть к чему придраться, накидвайся, можешь как Гоша:)

У меня правда есть вопросик - с Alignment, изначально я хотел все последовательно класть, но так нельзя, потому что все int переменные должны лежать на позициях кратных 4. Есть ли более красивый способ это сделать, чем я сейчас это сделал?

2023-10-21 22:27 UTC, AlexeyShik commented
> У меня правда есть вопросик - с Alignment, изначально я хотел все последовательно класть, но так нельзя, потому что все int переменные должны лежать на позициях кратных 4. Есть ли более красивый способ это сделать, чем я сейчас это сделал?

Можно было использовать java.lang.foreign.ValueLayout#JAVA_INT_UNALIGNED

2023-10-21 22:47 UTC, AlexeyShik approved these changes
10 баллов. 
Изначальное решение не подходило под условие дз.

2023-10-21 22:47 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/grunskiialexey/MemorySegmentDao.java
> +            page = MemorySegment.NULL;
Тут тоже по-хорошему надо закрыть арену. Конечно, память еще не утекла, потому что ее еще не выделили, но все же.

2023-10-21 22:47 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/grunskiialexey/MemorySegmentDao.java
> +            offset += 4;
Вместо 4 лучше использовать `Integer.BYTES`, чтобы было очевиднее читающему ваш код.

2023-10-21 22:47 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/grunskiialexey/MemorySegmentDao.java
> +            MemorySegment resultKey = MemorySegment.ofArray(new byte[keyLength]);
Здесь вы копируете данные и вытаскиваете их в хип, хотя они могли быть вне хипа.
Лучше было бы использовать `java.lang.foreign.MemorySegment#asSlice`. В таком случае был бы аллоцирован только один объект, а не несколько + копирование байт.

2023-10-21 22:47 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/grunskiialexey/MemorySegmentDao.java
> +            int valueLength = page.get(ValueLayout.JAVA_INT, offset);
Если не совпала длина или сами ключи, лучше не читать само значение.

Если учитывать, что мы читаем все записи подряд и почти все из них не подходят к данному ключу, получается, что будет O(число записей в sstable) лишних аллокаций на get одного ключа.

2023-10-21 22:47 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/grunskiialexey/MemorySegmentDao.java
> +            MemorySegment resultKey = MemorySegment.ofArray(new byte[keyLength]);
Аналогично, в случае, если не совпали длины ключей, можно не читать сам ключ, соответственно, не делать лишнюю аллокацию.

То есть какой порядок я предлагаю:

- читаем длину ключа
- если длины ключей не совпали, то continue
- читаем ключ
- если ключи не совпали, то continue
- читаем значение и возвращаем entry

2023-10-21 22:51 UTC, merged