тесты на Windows
polis-vk/2023-nosql-lsm pull request #152
Opened 2023-10-12 12:33 UTC by osokindm

2023-10-12 12:34 UTC, osokindm commented
[Описание](https://github.com/polis-vk/2023-nosql-lsm/issues/142)

2023-10-12 12:36 UTC, osokindm commented
PersistentTest проверял на втором дз, проходили все тесты, кроме cleanUp()

2023-10-17 14:33 UTC, incubos requested changes

2023-10-17 14:33 UTC, incubos commented on src/test/java/ru/vk/itmo/PersistentTest.java
> +        dao.close();
Тест `cleanup()` ниже поломан.

2023-10-18 20:14 UTC, Artyomcool commented
Боюсь, если тесты не работают, то принять PR мы не можем.

2023-10-20 18:33 UTC, incubos commented
Внезапно тесты починились :)

2023-10-29 18:24 UTC, Artyomcool commented
Предлагаю тогда замёржить и накинуть 10 баллов за инициативу.

2023-11-25 13:23 UTC, merged