Емельянов Виталий, Политех, часть 3
polis-vk/2023-nosql-lsm pull request #154
Opened 2023-10-14 11:31 UTC by GenryEden

2023-10-17 14:37 UTC, incubos requested changes
Нужно разрешить конфликты.

2023-10-21 13:15 UTC, Marashov-Alexander commented
На вкладке files changed не должно быть изменений папок других студентов. Не смогу приступить к проверке до тех пор, пока это условие не выполнено.

2023-10-29 08:34 UTC, Marashov-Alexander approved these changes
Пока 12/20
Важные проблемы: 
1) постоянное создание и утечка арены при get. Кстати, а она нужна? При каждом get также происходит маппинг одних и тех же файлов с открытием FileChannel -5 баллов
2) Дублирование компаратора в InMemoryDao, хотя он у вас есть в отдельном файле -1 балл
3) Использование магических констант -1 балл
4) В файл и в имя файла записываются разные версии -1 балл

2023-10-29 08:34 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/InMemoryDao.java
> +                        + Long.toString(System.nanoTime(), Character.MAX_RADIX)
У вас flush пишет currentTimeMillis и nanoTime в имя файла, а dumpToFile дергает эти же методы, но записывает их в файл. При этом пара currentTimeMillis + nanoTime гарантированно будет отличаться, так как между вызовами пройдет какое-то время. Получается, что сейчас в такой связке нет смысла. 

На мой взгляд, было бы удобнее использовать информацию из имени файла, так как имя файла уже будет у вас в конструкторе при создании экземпляра FileIterator, а вот время из самого файла нужно читать, что занимает время. И можно подумать о кэшировании currentTimeMillis после старта дао, так как файлы на диске неизменяемые. 

И почитайте, пожалуйста, доку про nanoTime: возможно это не то, что вы ожидаете) На разных машинах вызов nanoTime в одно и то же время вроде как даст разный результат. И вообще это не время в классическом понимании

2023-10-29 08:34 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/FileMergeIterator.java
> +    public Entry<MemorySegment> next() {
мб будет легче проверить наличие и достать нужный элемент через уже реализованный hasNext?

2023-10-29 08:34 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/FileMergeIterator.java
> +        return ans;
Кажется, есть смысл поддержать контракт итератора при вызове метода next?

"NoSuchElementException – if the iteration has no more element"

2023-11-01 18:17 UTC, Marashov-Alexander commented
15/20.
Важная проблема - выбор следующего FileIterator за O(количество файлов) -5 баллов.
И на будущее: будет здорово, если вы будете отвечать на комментарии ревьювера - так наша с вами работа будет продуктивнее :)

2023-11-01 19:37 UTC, GenryEden commented
> 15/20. Важная проблема - выбор следующего FileIterator за O(количество файлов) -5 баллов. И на будущее: будет здорово, если вы будете отвечать на комментарии ревьювера - так наша с вами работа будет продуктивнее :)

хорошо))

2023-11-01 20:13 UTC, incubos approved these changes

2023-11-01 20:21 UTC, merged