Тимофеев Кирилл, Магистратура ИТМО "Распределенные веб-сервисы", задание 3
polis-vk/2023-nosql-lsm pull request #160
Opened 2023-10-16 19:18 UTC by NoGe4Ek

2023-10-22 19:22 UTC, incubos requested changes
Есть большое количество вопросов и замечаний: как по эффективности, так и по корректности в целом. Тем не менее, готов дать 10 баллов за самостоятельное самобытное, пусть и переусложнённое, решение. Жду ответов на вопросы и исправления перед merge.

2023-10-22 19:22 UTC, incubos commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +            Deque<Entry<MemorySegment>> list = entries.get(number);
Зачем делать ещё один lookup? Это довольно горячий код реализации range-запросов. Почему не `entries.entries().iter`?

2023-10-22 19:22 UTC, incubos commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +class MemFileIterator implements Iterator<Entry<MemorySegment>> {
Чрезвычайно переусложнённая реализация: большое количество аллокаций (и это в `Iterator`!), совершенно не очевидно отсутствие багов, очень высокая когнитивная сложность. Вы сами видели на занятии и/или в reference, что можно гораздо проще.

2023-10-26 16:51 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/FactoryImpl.java
>  public class FactoryImpl implements DaoFactory.Factory<MemorySegment, Entry<MemorySegment>> {
Да, вы ее обратно смержили (когда изменения подмерживали) я подумал важна история. Удалил

2023-10-26 16:56 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +        if (!isInit) {
🖤

2023-10-26 17:13 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/FTIterator.java
> +        Collection<Entry<MemorySegment>> fromToMap;
Done

2023-10-26 17:13 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/FTIterator.java
> +        throw new UnsupportedOperationException("Remove is not supported");
Done

2023-10-26 17:13 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/FileEntry.java
> +record FileEntry(Entry<MemorySegment> entry, Long number) {
Done

2023-10-26 17:14 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/FilteredNullFTIterator.java
> +        throw new UnsupportedOperationException("Remove is not supported");
Done

2023-10-26 17:41 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/FilteredNullFTIterator.java
> +        this.iterator = fromToMap.stream().filter(v -> v.value() != null).iterator();
Done

2023-10-26 17:44 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/MSNumberComparator.java
> +            }
Done

2023-10-26 17:45 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        latestFileIndex = readConfig();
Done

2023-10-26 17:51 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        this.ssTablePath = path.resolve(Constants.FILE_NAME_PEFIX);
Done

2023-10-26 17:55 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            MemorySegment configMemorySegment = FileChannel.open(configPath, Constants.READ_OPTIONS)
У меня ничего не подсвечивается, настройки стандартные.
Done

2023-10-26 18:03 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            var readMappedMemorySegment = readMappedMemorySegments.getOrDefault(i, readFileAtIndex(i));
Потерялся. У нас целая лекция была про вары, мне показалось, что var везде будет хорошо смотреться. Потом сказали, что им не нужно злоупотреблять и я понял, что это не котлиновский вар - все убрал

2023-10-26 18:03 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            var readMappedMemorySegment = readMappedMemorySegments.getOrDefault(i, readFileAtIndex(i));
Done

2023-10-26 18:10 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            var readMappedMemorySegment = readMappedMemorySegments.getOrDefault(i, readFileAtIndex(i));
Из-за плохого подхода держать это все в памяти не проходил какой-то из тестов на память в хипе

2023-10-26 18:12 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            var readMappedMemorySegment = readMappedMemorySegments.getOrDefault(i, readFileAtIndex(i));
Done

2023-10-26 18:16 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +                continue;
Если ничего дополнительно не обговаривать, то да, является
Done

2023-10-26 18:17 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        Path ssTableNumPath = Paths.get(ssTablePath + Long.toString(index));
Done

2023-10-26 18:26 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        return readMappedMemorySegments.put(index, tryReadMappedMemorySegment);
Оч крутое замечание, спасибо
Done

2023-10-26 18:32 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            tryReadMappedMemorySegment = FileChannel.open(ssTableNumPath, Constants.READ_OPTIONS)
Поправил все утечки
Done

2023-10-26 18:39 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            tryReadMappedMemorySegment = null;
Теперь имеет смысл. computeIfAbsent не положит null

2023-10-26 18:39 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            tryReadMappedMemorySegment = null;
Теперь имеет смысл. computeIfAbsent не положит null

2023-10-26 18:41 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +                             long offset, MemorySegment key, long biteCount) {
По смыслу да, только никто не гарантирует, что страница будет начинаться с места, где мы закончили считывать с диска. Я это понимаю, но почему-то захотелось сделать иммитацию префетча

2023-10-26 18:42 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +    private long calculateTotalSize(long keySize, long valueSize, long offset) {
sry. код климат иногда слишком жесток. Удобнее было до этого комментариями в коде разбить на части. Лично мне проще читалось и понятнее было, а климат заставляет лишнее накидывать

2023-10-26 18:50 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +                currentOffset -= Long.BYTES;
Да, комментариев правда не хватает, не буду оправдываться
Это скорее не случай, а алгоритм. Почему-то мне снова показалось, что имитировать подгрузку страницами из памяти будет эффективно. Тут проверяем, что считали 4кб

2023-10-26 18:52 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            } else {
Да, это правда. Недавно разбирался с clang-tidy и clazy. Там как раз есть чекеры на такие вещи, тк это плохо читается и дольше выполняется

2023-10-26 18:52 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            } else {
Done

2023-10-27 16:18 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +                processKeySize(keySize, key.byteSize(), offsets, currentOffset - Long.BYTES);
Done

2023-10-27 16:19 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +                if (keySize > key.byteSize()) {
Fixed

2023-10-27 16:59 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            offsets.add(offset);
Действительно, наивная реализация. Я уже видел на паре, что можно намного эффективнее. Но нужно было во время реализации откатиться до механизма записи в сстэйбл. А я не додумался хранить офсеты отдельно, вместе с данными, пришлось городить

2023-10-27 17:05 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +    private long updateOffset(long keySize, long valueSize, long offset) {
Большая часть функций вообще не должна была появиться на свет. Код климат навязал.
Done

2023-10-27 17:06 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +            int mid = left + (right - left) / 2;
👍

2023-10-27 17:13 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        writeArena.close();
Fixed

2023-10-27 17:13 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        writeConfigArena.close();
Fixed

2023-10-27 17:18 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        while (offset < sstable.byteSize()) {
Ничем и это проблема, соглашусь

2023-10-27 17:20 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        MemorySegment writeMappedMemorySegment = FileChannel.open(ssTableNumPath, Constants.WRITE_OPTIONS)
Fixed

2023-10-27 17:20 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        Path ssTableNumPath = Paths.get(ssTablePath + Long.toString(latestFileIndex + 1));
Fixed

2023-10-27 17:20 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +        MemorySegment writeConfig = FileChannel.open(path.resolve(Constants.FILE_NAME_CONFIG), Constants.WRITE_OPTIONS)
Fixed

2023-10-27 17:21 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +        isInit = false;
А почему бы и нет, его в параметрах конструктора нет, имя не повторяется. Но с this читается проще. Fixed

2023-10-27 17:30 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +                entry.getValue().add(new BaseEntry<>(keyMemorySegment, valueMemorySegment));
Это действительно так, но почему-то в моей реальности я склонялся к варианту использования, при котором из нас всегда читают большими кусками и next будет вызываться много. Причем операция чтения дорогая

2023-10-27 17:30 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +            while (offset < Constants.PAGE_SIZE * biteCount && offset < readMappedMemorySegment.byteSize()) {
👍

2023-10-27 17:36 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +            Deque<Entry<MemorySegment>> list = entries.get(number);
Да, на итераторах хранить ничего не приходится

2023-10-27 17:41 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +class MemFileIterator implements Iterator<Entry<MemorySegment>> {
Спасибо за комментарии, много полезного узнал. Больно дальше это развивать, главное, что разобрался в принципе работы. Дальше буду с референсом работать

2023-10-29 11:06 UTC, incubos commented on src/main/java/ru/vk/itmo/timofeevkirill/InMemoryDao.java
> +    private long updateOffset(long keySize, long valueSize, long offset) {
Code Climate разве что-то навязывает? :) Он лишь говорит, что код сложный и нужно упрощать. Множество проектов используют его платную версию не для того, что разработчикам что-то навязывали.

2023-10-29 11:07 UTC, incubos commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +        isInit = false;
Можно и без, но тогда везде давайте одинаково.

2023-10-29 11:09 UTC, incubos commented on src/main/java/ru/vk/itmo/timofeevkirill/MemFileIterator.java
> +class MemFileIterator implements Iterator<Entry<MemorySegment>> {
Смотрите сами, но продолжать развивать свою реализацию гораздо интереснее :(

2023-10-29 11:11 UTC, incubos commented
10 баллов.

2023-10-29 11:11 UTC, incubos approved these changes

2023-10-29 11:11 UTC, merged