Пелогейко Макар Андреевич, ИТМО DWS, Task 3
polis-vk/2023-nosql-lsm pull request #161
Opened 2023-10-17 11:26 UTC by makar-pelogeiko

- Trial implementation

2023-10-17 14:38 UTC, incubos requested changes
Нужно разрешить конфликты.

2023-10-29 20:09 UTC, vladimir-bf approved these changes
есть недочеты в работе с memorysegment  и аренами и вопросы по производительности решения
также, код стайл местами вызывает сомнения

12 баллов

2023-11-07 14:59 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/pelogeikomakar/Triple.java
> +public class Triple<A, B, C> {
Изначально этого не было.
Я не мог пройти кодстайл без добавления данного метода

2023-11-25 13:35 UTC, incubos commented
Проставил в ведомость.

2023-11-25 13:35 UTC, closed without merging