Hw3 Ершов Вадим
polis-vk/2023-nosql-lsm pull request #163
Opened 2023-10-17 18:00 UTC by vadim01er

2023-10-24 21:12 UTC, atimofeyev requested changes

2023-10-24 21:12 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        arena = Arena.ofConfined();
это не будет работать в многопоточной среде

2023-10-24 21:12 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        Iterator<Entry<MemorySegment>> iterator = get(key, null);
в такой реализации get мы делаем слишком много лишней рабты с итераторами

2023-10-24 21:12 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +                    msIndex.set(ValueLayout.JAVA_LONG_UNALIGNED, indexOffset, tableOffset);
здесь мы неэффективно скачем по памяти когда пишем то в индекс то в значения, эффективнее было бы читать сначала целиком индекс а потом значения

2023-10-24 21:49 UTC, vadim01er commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +                    msIndex.set(ValueLayout.JAVA_LONG_UNALIGNED, indexOffset, tableOffset);
у меня индекс и данные это разные файлы, вероятно тут проблем не должно быть или я ошибаюсь?

2023-10-24 21:51 UTC, vadim01er commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        Iterator<Entry<MemorySegment>> iterator = get(key, null);
в итоге практик на прошлой паре реализовал похожий алгоритм, пока что у меня не получилось придумать наиболее быстрый алгоритм

2023-10-24 21:52 UTC, vadim01er commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        arena = Arena.ofConfined();
да, тут я ошибся не проверил тип арены

2023-10-25 20:09 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +                    msIndex.set(ValueLayout.JAVA_LONG_UNALIGNED, indexOffset, tableOffset);
да, все верно, и в одном файле скорее всего не было бы проблем )

2023-10-25 20:10 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        Iterator<Entry<MemorySegment>> iterator = get(key, null);
тут мы создаем кучу итераторов, хотя можно сходить просто по гет, к тому же если найдем в памяти то вообще не придется ничего делать с сс таблицами

2023-10-25 20:15 UTC, vadim01er commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        Iterator<Entry<MemorySegment>> iterator = get(key, null);
да, можно было вызвать из памяти и если у нас нет в памяти вызвать мердж итератор, правильно понимаю?
или не итератор даже, а пройтись по приоритетам файлов бинарным поиском и как только находим первый попавшийся выводим (либо null, либо Entry)?

2023-10-25 20:25 UTC, vadim01er commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        Iterator<Entry<MemorySegment>> iterator = get(key, null);
я не совсем понимаю какую конкретно реализацию вы предлагаете мне сделать

2023-10-25 20:27 UTC, vadim01er commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +                    msIndex.set(ValueLayout.JAVA_LONG_UNALIGNED, indexOffset, tableOffset);
ну просто скачков по памяти в данном случае нет, раз два mmap файла?

2023-10-28 13:23 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        Iterator<Entry<MemorySegment>> iterator = get(key, null);
да, все верно, вообще без итераторов, мы можем искать в порядке приоритета бинарным поиском

2023-10-28 13:36 UTC, atimofeyev requested changes

2023-10-28 13:36 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +            try (var fcTable = FileChannel.open(ssTableDir.resolve(DATA), TRUNCATE_EXISTING, CREATE, WRITE, READ);
в этом случае лучше создавать файлы без TRUNCATE_EXISTING, что если там уже лежит файл с таким именем?

2023-10-28 13:36 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/SSTable.java
> +        Path dataFile = dir.resolve(PersistenceManyFilesDao.DATA);
плохая пактика делать такие циклические ссылки, ДАО зависит от этого класса, и получается что этот класс зависит от переменных в ДАО (PersistenceManyFilesDao.DATA)

2023-10-28 13:36 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/SSTable.java
> +                dir.getFileName().toString().substring(PersistenceManyFilesDao.SS_TABLE_DIR.length())
если имя будет начинаться не с SS_TABLE_DIR?
Я понимаю что вы выше проверили, но хорошая практика если в классе есть какое-то требование к формату - проверить его на входе, в целом все равно будет ошибка, но лучше когда это явно определено

2023-10-28 13:36 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/ershovvadim/hw3/PersistenceManyFilesDao.java
> +        Path ssTableDir = dir.resolve(SS_TABLE_DIR + ssTables.size());
назначать ИД таким образом опасно (ssTables.size())
но на текущем этапе сойдет

2023-10-28 13:36 UTC, atimofeyev approved these changes

2023-10-28 13:37 UTC, atimofeyev commented
13 баллов

2023-10-28 13:49 UTC, merged