Пронин Валентин, Магистратура ИТМО "Распределенные веб-сервисы", 3 лабораторная
polis-vk/2023-nosql-lsm pull request #171
Opened 2023-10-18 12:54 UTC by GonarchX

2023-10-24 20:47 UTC, atimofeyev requested changes

2023-10-24 20:47 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/FileDao.java
> +                    entryOffset = MemorySegmentUtils.writeEntryOffset(
вот здесь мы пишем каждую итерацию в разные области памяти, было бы более эффективно сначала записать офсеты а потом сами значения

2023-10-24 20:47 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/FileDao.java
> +        String writeValuesFileName = FileUtils.getNewFileName(basePath, VALUES_FILENAME_PREFIX);
здесь есть опасность записать битый файл и потом не подняться из-за него

2023-10-24 20:47 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/utils/FileUtils.java
> +        while (i > 0 && Character.isDigit(fileName.charAt(i - 1))) {
если вдруг в папке окажется файл с именем не содержащим цифры - быть беде

2023-10-24 20:47 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/utils/MemorySegmentUtils.java
> +        localFileOffset = writeMemorySegment(src.key(), dst, localFileOffset);
здесь мы расходуем больше памяти чем могли бы, на занятии был показан более эффективный вариант сохранения индекса и значений

2023-10-24 20:47 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/iterators/MergeIterator.java
> +        var nonEmptyFileIterators = inFileIterators.stream().filter(Iterator::hasNext).toList();
а зачем тут var?

2023-10-25 06:28 UTC, GonarchX commented on src/main/java/ru/vk/itmo/proninvalentin/utils/MemorySegmentUtils.java
> +        localFileOffset = writeMemorySegment(src.key(), dst, localFileOffset);
А у нас же для третьей лабораторной был референс только на вторую лабу, где, если я не ошибаюсь, тоже использовали файл с оффсетами на Entry и файл, который содержит Entry в следующем виде: |KeySize|Key|ValueSize|Value|

2023-10-25 06:33 UTC, GonarchX commented on src/main/java/ru/vk/itmo/proninvalentin/utils/FileUtils.java
> +        while (i > 0 && Character.isDigit(fileName.charAt(i - 1))) {
Как лучше поступить: выбрасывать исключение если файл не содержит индекс и при этом обладает нужным префиксом?
Просто в текущей реализации все создаваемые мною файлы должны содержать префикс "values" или "offsets" и обладать индексом. Если есть файл с таким префиксом, но не имеет индекса, то `Integer.parseInt` тоже выкинет исключение

2023-10-25 06:33 UTC, GonarchX commented on src/main/java/ru/vk/itmo/proninvalentin/iterators/MergeIterator.java
> +        var nonEmptyFileIterators = inFileIterators.stream().filter(Iterator::hasNext).toList();
Исправил

2023-10-25 06:44 UTC, GonarchX commented on src/main/java/ru/vk/itmo/proninvalentin/FileDao.java
> +                    entryOffset = MemorySegmentUtils.writeEntryOffset(
Поправил

2023-10-25 07:03 UTC, GonarchX commented on src/main/java/ru/vk/itmo/proninvalentin/DaoFacade.java
> +        // Сначала ищем в памяти
Не очень понял мысль

Если мы добавим это условие, то будет возможна ситуация, когда ms будет равен null, соответственно второе условие `ms.value() == null` выкинет исключение "NullPointerException"

К тому же, у нас в тестах есть условие, что MemorySegment'ы со значением null должны возвращать null, а не MemorySegment с ключом и значением null.
![image](https://github.com/polis-vk/2023-nosql-lsm/assets/62358071/77be5358-19a3-4c1f-aba2-faa5334ee86b)

2023-10-25 07:12 UTC, GonarchX commented on src/main/java/ru/vk/itmo/proninvalentin/DaoFacade.java
> +            if (msFromFiles == null || msFromFiles.value() == null) {
Так а мы же тут проверяем найден MemorySegment и не удален ли он, если так, то можем его вернуть, иначе возвращаем null.

Можно конечно убрать `else` ветку и сразу возвращать `msFromFiles`
```
if (ms == null && fileDao != null) {
            Entry<MemorySegment> msFromFiles = fileDao.read(key);
            if (msFromFiles == null || msFromFiles.value() == null) {
                return null;
            }
            return msFromFiles;
        }
```

А насчет "сделать так, чтобы не пришлось постоянно проверять", это как? Нам же все равно каждый раз нужно смотреть не был ли удален желаемый MemorySegment и есть ли он вообще

2023-10-25 07:58 UTC, GonarchX commented on src/main/java/ru/vk/itmo/proninvalentin/FileDao.java
> +        String writeValuesFileName = FileUtils.getNewFileName(basePath, VALUES_FILENAME_PREFIX);
Поправил, теперь сначала создается временный файл для оффсетов и значений, а после успешной записи, временные файлы переименовываются в обычный формат. Правда из-за того, что файла два, переименование происходит не атомарно.

2023-10-25 19:55 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/utils/MemorySegmentUtils.java
> +        localFileOffset = writeMemorySegment(src.key(), dst, localFileOffset);
в третьей нам уже надо делать бинарный поиск и референс со второй уже не подходил, но в целом то так тоже работает, просто это точка оптимизации

2023-10-25 19:55 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/utils/FileUtils.java
> +        while (i > 0 && Character.isDigit(fileName.charAt(i - 1))) {
я думаю что можно просто пропускать его

2023-10-25 19:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/FileDao.java
> +        String writeValuesFileName = FileUtils.getNewFileName(basePath, VALUES_FILENAME_PREFIX);
да можно все и в один файл писать в целом все равно, мой пойнт был чтобы писать последовательно, но и это не факт что будет эффективнее, тут я может погорячился

2023-10-25 19:58 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/DaoFacade.java
> +            if (msFromFiles == null || msFromFiles.value() == null) {
это долго писать как, но даю гарантию что можно организовать код по-другому что будет меньше проверок на нулл, мне кажется в референсе от Артема их меньше )

2023-10-25 19:59 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/DaoFacade.java
> +        // Сначала ищем в памяти
ну я опечатлася, имел ввиду if (ms == null || ms.value() == null)

2023-10-25 20:00 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/DaoFacade.java
> +        // Сначала ищем в памяти
тогда просто ниже не пришлось бы на нулл еще раз проверять

2023-10-25 20:02 UTC, atimofeyev approved these changes

2023-10-25 20:07 UTC, atimofeyev requested changes

2023-10-25 20:07 UTC, atimofeyev commented on src/test/java/ru/vk/itmo/ReopenRangeTest.java
> +package ru.vk.itmo;
а почему поменян файл тестов? лучше чтобы тут не было дифов

2023-10-25 20:22 UTC, GonarchX commented on src/test/java/ru/vk/itmo/ReopenRangeTest.java
> +package ru.vk.itmo;
Я вот кстати не знаю почему гит вообще решил, что это в этом файле поменялось все содержимое, учитывая, что содержимое абсолютно одинаковое.
Я в него добавлял свои тесты в процессе разработки, но перед пушем откатил изменения

2023-10-27 09:49 UTC, atimofeyev commented on src/test/java/ru/vk/itmo/ReopenRangeTest.java
> +package ru.vk.itmo;
скорее всего у вас windows и расставились свои окончания строк, лучше выставить в настройках ИДЕ такие же как в линуксе

2023-10-27 13:31 UTC, GonarchX commented on src/test/java/ru/vk/itmo/ReopenRangeTest.java
> +package ru.vk.itmo;
Странно, поставил как для линукса и макоса, git подцепил изменения, я их отправил на сервер, а ничего не поменялось, да и `git ls-files --eol` тоже показывает, что там окончания строк как для линукса и макоса
![tg_image_3220850228](https://github.com/polis-vk/2023-nosql-lsm/assets/62358071/109cfc6b-5148-44d0-92d4-99c67839aa59)

2023-10-28 13:39 UTC, atimofeyev commented on src/test/java/ru/vk/itmo/ReopenRangeTest.java
> +package ru.vk.itmo;
надо с этим что-то сделать ), мержить такой файл не хочется.
Есть еще настройке в самом гите помимо ИДЕ, проверьте там тоже

2023-10-28 13:52 UTC, atimofeyev requested changes

2023-10-28 13:52 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/FileDao.java
> +                StandardOpenOption.TRUNCATE_EXISTING);
в данном случае лучше не перетирать файл, вдруг он уже есть с таким именем.
Да и писать лучше файл сначала в tmp, а потом атомарно его переименовать
Если мы упадем в процессе записи в файл с нормальным именем, потом на старте мы его не сможем прочитать

2023-10-28 13:52 UTC, atimofeyev approved these changes

2023-11-03 19:29 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/proninvalentin/FileDao.java
> +                StandardOpenOption.TRUNCATE_EXISTING);
16 баллов, но чтобы мержить - поправьте сначала файл с тестами, замержить файл желательно перед следующим этапом но в таком виде мержить не хочется

2023-11-04 09:07 UTC, GonarchX commented on src/main/java/ru/vk/itmo/proninvalentin/FileDao.java
> +                StandardOpenOption.TRUNCATE_EXISTING);
Решил создать [отдельную ветку](https://github.com/polis-vk/2023-nosql-lsm/pull/249)
Эту, я думаю, можно просто закрыть и не мержить в main

2023-11-04 22:40 UTC, closed without merging