Качмар Евгений, ИТМО ФИТиП М33331, HW3
polis-vk/2023-nosql-lsm pull request #172
Opened 2023-10-18 13:40 UTC by Jenshen30

2023-11-01 18:02 UTC, Dalvikk requested changes

2023-11-01 18:04 UTC, Dalvikk commented
По -2 за мажор и -1 за минор, пока 13 баллов. Если пофиксишь и зашлешь на повторное ревью будет больше :)

2023-11-05 17:20 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTablesController.java
> +import static java.nio.file.StandardOpenOption.CREATE;
Ой, раньше об этом не задумывался, буду иметь в виду)

2023-11-05 17:22 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTableRowInfo.java
> +    int ssTableInd;
Да, это так, пофиксил.

2023-11-05 17:22 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/InMemoryDao.java
> +            if (mp.get(key).value() == null) {
исправил

2023-11-05 17:23 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTableRowInfo.java
> +    public long totalShift() {
убрал

2023-11-05 17:26 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTableIterator.java
> +        insertNew(controller.getNextInfo(oldInfo, to));
на JIT лучше не полагаться никогда?
Так или иначе, исправил

2023-11-05 17:26 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTableIterator.java
> +        if (!mp.containsKey(kv.key())) {
Из-за сложности восприятия это стоило бы заменять?
Тем не менее исправил

2023-11-05 17:26 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTablesController.java
> +        Set<OpenOption> options = Set.of(WRITE, READ, CREATE);
fixed

2023-11-05 17:28 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTableIterator.java
> +        memTableIterator = it;
исправил

2023-11-05 17:28 UTC, Jenshen30 commented on src/main/java/ru/vk/itmo/test/kachmareugene/MemSegComparatorNull.java
> +
1. Подумал сделать `null` одновременно и +inf и -inf. Так было удобно в некоторых сравнениях
2. Да, хорошая идея. Пофиксил:)

2023-11-12 18:35 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTableIterator.java
> +        if (!mp.containsKey(kv.key())) {
Я так понимаю ты ты имешь ввиду что предложенный код сложнее чем map.contains() и map.get()?
Тут речь о том же, о чем выше: два вызова к многопоточной структуре когда можно обойтись одним. putIfAbsent не такой сложный для восприятия метод, и разработчик который работает с многопоточными структурами как правило знает что он делает и зачем нужен

2023-11-12 18:36 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/test/kachmareugene/SSTableIterator.java
> +        insertNew(controller.getNextInfo(oldInfo, to));
Ага, лучше не полагаться. Даже если ты уверен что это оптимизируется, другой разработчик который будет читать код нет

2023-11-12 18:40 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/test/kachmareugene/MemSegComparatorNull.java
> +
1. Это интуитивно не понятно и странно, это надо держать в голове всегда. Сложно для восприятия как минимум другому разработчику. Лучше все таки сделать по нормальному
2. А зачем исключение вместо 0?

2023-11-12 18:46 UTC, Dalvikk approved these changes
19 баллов

2023-11-12 18:47 UTC, merged