Прокопьев Никита, Магистратура ИТМО "Распределенные веб-сервисы" 3 лабораторная
polis-vk/2023-nosql-lsm pull request #173
Opened 2023-10-18 19:31 UTC by Nikpro200125

2023-10-20 18:16 UTC, incubos requested changes
Нужно разрешить конфликты.

2023-10-29 18:47 UTC, Artyomcool approved these changes
По-моему, прекрасная работа, 20 баллов.

2023-11-23 15:48 UTC, Nikpro200125 commented
@Artyomcool, вы не выставили баллы на портал, могли бы ,пожалуйста, проставить. И нужно ли мне разрешать конфликты в ветке?

2023-11-24 12:06 UTC, incubos commented
Проставил баллы. Конфликты разрешать уже не нужно.

2023-11-24 12:06 UTC, closed without merging