HW2 Дягай, Политех
polis-vk/2023-nosql-lsm pull request #177
Opened 2023-10-18 20:10 UTC by fo-xi

2023-10-29 21:00 UTC, lamtev requested changes
Решение выглядит самостоятельным и интересным. Тем не менее новый API MemorySegment используется исключительно чтобы реализовать интерфейсы. А его возможности не используются. Множество избыточных аллокаций и неэффективного использования ресурсов

В текущем виде решение может быть оценено в 10 баллов

2023-10-29 21:00 UTC, lamtev commented on src/main/java/ru/vk/itmo/dyagayalexandra/Storage.java
> +            if (new MemorySegmentComparator().compare(key, next.key()) == 0) {
Имеет смысл закэшировать в финальном статическом поле компаратор, чтобы избежать аллокаций на каждый вызов данного метода

2023-10-29 21:00 UTC, lamtev commented on src/main/java/ru/vk/itmo/dyagayalexandra/FileManager.java
> +        return new BaseEntry<>(MemorySegment.ofArray(key.array()), MemorySegment.ofArray(value.array()));
Много аллокаций

2023-11-02 22:07 UTC, fo-xi commented on src/main/java/ru/vk/itmo/dyagayalexandra/Storage.java
> +            if (new MemorySegmentComparator().compare(key, next.key()) == 0) {
исправлено

2023-11-02 22:08 UTC, fo-xi commented on src/main/java/ru/vk/itmo/dyagayalexandra/FileManager.java
> +        return new BaseEntry<>(MemorySegment.ofArray(key.array()), MemorySegment.ofArray(value.array()));
исправлено, использованы методы нового API MemorySegment

2023-11-15 22:32 UTC, lamtev commented
15 баллов

2023-11-15 22:32 UTC, lamtev approved these changes

2023-11-15 22:33 UTC, merged