Коротких Виктор / ИТМО DWS / Stage 3
polis-vk/2023-nosql-lsm pull request #180
Opened 2023-10-18 20:39 UTC by vitekkor

2023-10-18 21:07 UTC, vitekkor commented
Почему-то не проходят тесты на CI, хотя локально всё ок.

На гифке видно, что ветка актуальная, никаких дополнительных изменений в код не было сделано, тесты проходят.

![Peek 2023-10-19 00-04](https://github.com/polis-vk/2023-nosql-lsm/assets/36002722/a4b4d3cc-f7df-4e2e-8274-a6769b25677d)

Также пробовал запускать из консоли через ./gradlew build (как в CI), результат тот же:

![Peek 2023-10-19 00-07](https://github.com/polis-vk/2023-nosql-lsm/assets/36002722/d7faf068-0542-49f9-b425-dd15fb71ebbb)

2023-10-19 09:28 UTC, incubos commented
У меня тесты локально не проходят (linux как и на агентах):
```
$ ./gradlew clean test
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/incubos/tmp
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/incubos/tmp
Note: Some input files use preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.

> Task :compileTestJava
Note: /home/incubos/devel/review/vitekkor/2023-nosql-lsm/src/test/java/ru/vk/itmo/DaoTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/incubos/tmp

Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 0 from 1 ==> expected: <{k0000000001:v0000000001}> but was: <{k0000000001:removable}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: expected: <null> but was: <{k0000000001:removable}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: No more entries in iterator: 0 from 1 entries iterated' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "obj" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 18 from 42 ==> expected: <{k0000000061:v0000000061}> but was: <{k0000000030:v0000000030}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: No more entries in iterator: 0 from 1 entries iterated' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "obj" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 0 from 3 ==> expected: <{k0000000007:v0000000007}> but was: <{k0000000007:old7}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 1 from 3 ==> expected: <{k0000000097:v0000000097}> but was: <{k0000000097:old97}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: expected: <{key:value2}> but was: <{key:value1}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null

> Task :test

PersistentDeletionTest > restoreOldValueInFile(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at PersistentDeletionTest.java:75

PersistentDeletionTest > deleteOldValueFromFile(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at PersistentDeletionTest.java:25

PersistentDeletionTest > restoreOnDisk(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at PersistentDeletionTest.java:111

PersistentDeletionTest > checkFlow(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at PersistentDeletionTest.java:210

PersistentDeletionTest > rangeStressTest(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at PersistentDeletionTest.java:160

PersistentRangeTest > fresh(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at PersistentRangeTest.java:17

PersistentRangeTest > replaceOnDisk(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at PersistentRangeTest.java:17

PersistentTest > replaceWithClose(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at PersistentTest.java:104

Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 1 from 3 ==> expected: <{k2:4}> but was: <{k2:2}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 0 from 10000 ==> expected: <{k0000000000:new0000000000}> but was: <{k0000000000:old0000000000}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 0 from 2 ==> expected: <{k2:4}> but was: <{k2:2}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 0 from 3 ==> expected: <{k2:4}> but was: <{k2:2}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 1 from 3 ==> expected: <{k2:4}> but was: <{k2:2}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 1 from 4 ==> expected: <{k2:4}> but was: <{k2:2}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError: wrong entry at index 3 from 5 ==> expected: <{k0000000004:v0000000004}> but was: <{k0000000003:v0000000003}>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4816278d': Cannot invoke "Object.getClass()" because "expectedValue" is null

> Task :test FAILED

ReopenRangeTest > allToRange(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at ReopenRangeTest.java:105

ReopenRangeTest > testManyFiles(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at ReopenRangeTest.java:170

ReopenRangeTest > rangeInTheMiddle(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at ReopenRangeTest.java:127

ReopenRangeTest > allFromRange(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at ReopenRangeTest.java:83

ReopenRangeTest > onlyPersistence(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at ReopenRangeTest.java:26

ReopenRangeTest > withInMemory(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at ReopenRangeTest.java:60

UpsertRemoveTest > manyRemoveRecords(Dao) > [1] TestDao<viktorkorotkikh.LSMDaoImpl> FAILED
    org.opentest4j.AssertionFailedError at UpsertRemoveTest.java:9 [...]

2023-10-19 09:29 UTC, incubos commented
CodeClimate сломался на `sealed` -- посмотрю.

2023-10-19 10:19 UTC, vitekkor commented
@incubos Хм, кажется дело в сортировке путей к файлам. У меня на арче jvm изначально выдаёт их в "правильном" для меня порядке - sstable0.db, sstable1.db ,sstable2.db и т.д. 

Если CodeClimate фиксить не удобно, то могу отказаться от sealed

2023-10-19 10:21 UTC, incubos commented
> @incubos Хм, кажется дело в сортировке путей к файлам. У меня на арче jvm изначально выдаёт их в "правильном" для меня порядке - sstable0.db, sstable1.db ,sstable2.db и т.д.
> 
> Если CodeClimate фиксить не удобно, то могу отказаться от sealed

Да, давайте пока откажемся от `sealed`. Не уверен, что смогу быстро разобраться и пофиксить.

2023-10-19 10:32 UTC, incubos commented
Теперь `sealed` должен поддерживаться, как и все фичи 21.

2023-10-23 20:43 UTC, atimofeyev requested changes

2023-10-23 20:43 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/viktorkorotkikh/SSTable.java
> +                mappedSSTableFile.set(
Было бы более эффективно сначала сохранить индекс а потом данные, сейчас вы постоянно прыгаете по памяти, что может быть неэффективно (помним про page cache)

2023-10-23 20:55 UTC, vitekkor commented on src/main/java/ru/vk/itmo/viktorkorotkikh/SSTable.java
> +                arena = Arena.ofShared();
Нет, здесь на каждый SSTable своя арена. Специально не вносил в try-with-resources, потому что арена для каждого SSTable зыкрывается в методе close(), который в свою очередь вызывается из метода close класса LSMDaoImpl

https://github.com/polis-vk/2023-nosql-lsm/pull/180/files#diff-79201a9f5547826a664aaebf9109694f27b9f047da9deda3ae6bc1800e3e5aeeR73

```java
    @Override
    public void close() throws IOException {
        ssTables.forEach(SSTable::close);
        SSTable.save(storage.values(), ssTables.size(), storagePath);
    }
```

Возможно, я не до конца понял концепцию арен, но в моём понимании - если тут закрыть арену, то мы не сможем читать из sstable, так как связанная с замаппленным MemorySegment арена (собственно, вот эта самая, которую мы закрыли) будет уже закрыта

2023-10-24 10:35 UTC, vitekkor commented on src/main/java/ru/vk/itmo/viktorkorotkikh/SSTable.java
> +                mappedSSTableFile.set(
Исправил. Теперь сначала пишем индекс для наших данных, затем сами данные

2023-10-24 10:44 UTC, vitekkor commented on src/main/java/ru/vk/itmo/viktorkorotkikh/LSMDaoImpl.java
> +        Iterator<Entry<MemorySegment>> iterator = get(key, null);
Согласен, упустил из виду. Переписал на более оптимальный вариант, на мой взгляд

2023-10-24 20:50 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/viktorkorotkikh/SSTable.java
> +                arena = Arena.ofShared();
так эту арену мы никогда не закроем, тут мы создаем новую локальную shared арену, а закрываем ту что в поле класса хранится

2023-10-24 21:02 UTC, vitekkor commented on src/main/java/ru/vk/itmo/viktorkorotkikh/SSTable.java
> +                arena = Arena.ofShared();
> закрываем ту что в поле класса хранится

 Да, всё верно. Но в поле класса передаётся арена, которую мы тут создали в 76 строке. Или я не до конца понимаю, что Вы имеете в виду?

Какая задумка у меня была: вызываем _статический_ метод load, который возвращает список sstable (отсортированный по приоритетам от меньшего к большему). Этот метод в цикле итерируется по списку путей к файлам `sstable{index}.db`. Для каждого файла создаётся своя арена, которая в конечном итоге после выполнения mmap файла, попадает в приватный конструктор класса SSTable. В этом классе она становится полем, и на ней может быть вызван метод close() в методе close() класса SSTable. Этот метод close вызывается в методе close() LSMDaoImpl. 

LSMDaoImpl.close() -> forEach(SSTable::close()) -> SSTable.arena.close()


Такая вот сказка получается -  игла в яйце, яйцо в утке, утка в зайце

2023-10-24 21:18 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/viktorkorotkikh/SSTable.java
> +                arena = Arena.ofShared();
да, я понял, запутался слегка.
Но для всех таблиц можно переиспользовать одну арену, не стоит создавать их так много

2023-10-25 08:52 UTC, vitekkor commented on src/main/java/ru/vk/itmo/viktorkorotkikh/SSTable.java
> +                mappedSSTableFile.set(
Индекс пишем тут, а ниже пишем сами [данные](https://github.com/polis-vk/2023-nosql-lsm/pull/180/files#diff-b09a55fbd5a2ea7d28e29d9fa17f12c035b5adad8868ac3481d50ef1107caf0bR145)

2023-10-25 08:53 UTC, vitekkor commented on src/main/java/ru/vk/itmo/viktorkorotkikh/SSTable.java
> +                arena = Arena.ofShared();
Сделал общую shared арену для всех sstable

2023-10-25 09:16 UTC, atimofeyev approved these changes

2023-10-25 09:34 UTC, atimofeyev commented
15 баллов

2023-10-25 09:34 UTC, merged