HW4 Чеботин Александр (ITMO DWS)
polis-vk/2023-nosql-lsm pull request #195
Opened 2023-10-22 10:33 UTC by axothy

2023-11-11 13:40 UTC, atimofeyev requested changes

2023-11-11 13:40 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTablesStorage.java
> +                memorySegment.set(ValueLayout.JAVA_LONG_UNALIGNED, Long.BYTES + i * Byte.SIZE, offset);
здесь совсем не на месте Byte.SIZE
он конесно равен 8, но байт это 8 битов, а тут мы считаем в байтах
Лучше было бы использовать Long.BYTES

2023-11-11 13:40 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTablesStorage.java
> +            memorySegment.set(ValueLayout.JAVA_LONG_UNALIGNED, OFFSET_FOR_SIZE, COMPACTION_NOT_FINISHED_TAG);
не самый надежный вариант, может так получиться что мы запишем сюда нормальны рзамер, а дальше что-то будет недозаписано, лучше всего делать так как делал Артем на семинаре: пишем в тмп файл а потом его перемещаем.

В текущем решении вообще мы можем некорректно записать в тмп файл, потому удалить другие файлы.

2023-11-11 13:50 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTablesStorage.java
> +            memorySegment.set(ValueLayout.JAVA_LONG_UNALIGNED, OFFSET_FOR_SIZE, COMPACTION_NOT_FINISHED_TAG);
Я сначала записываю в tmp файл как раз, и только после записи всех entry я записываю в header размер. И только после факта записи размера считается что compaction завершен и перемещается файл. Если же размер не был записан (то есть записалось в header COMPACTION_NOT_FINISHED_TAG) означает что во время записи что-то пошло не так, и это проверяется в конструкторе. Если же размер все-таки записался, то это означает что записалось абсолютно все и осталось проверить в конструкторе если ли тмпшный файл или нет, если его нет - значит весь компакшн полностью завершен, а если он есть - то осталось просто доудалить старые таблицы и переместить тмп файл

2023-11-12 17:16 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTablesStorage.java
> +            memorySegment.set(ValueLayout.JAVA_LONG_UNALIGNED, OFFSET_FOR_SIZE, COMPACTION_NOT_FINISHED_TAG);
Так нет же никаких фактов записи

1. Вы думаете что все записили корректно, а на самом деле ничего не записалось
2. Удаляете все свои файлы

Не вижу никаких фактов проверки записи в коде после пункта 1

2023-11-13 22:17 UTC, atimofeyev approved these changes
17 баллов

2023-11-13 22:23 UTC, merged