ИТМО ФИТиП, Пологов Никита fix hw2
polis-vk/2023-nosql-lsm pull request #196
Opened 2023-10-22 13:09 UTC by y0f0

фикс замечаний из https://github.com/polis-vk/2023-nosql-lsm/pull/121

Assignees, Reviewers: @AlexeyShik

2023-10-22 21:41 UTC, AlexeyShik requested changes
Это нужно поправить

2023-10-22 21:41 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/pologovnikita/SSTable.java
> +            readPage = channel.map(FileChannel.MapMode.READ_ONLY, 0, fileSize, arena);
Тут не стоит сразу закрывать арену, потому что после закрытия арены нет гарантий, что мемори сегменты живы, в нашем случае unmap может произойти в любой момент. 
Скорее всего тесты просто слишком быстрые и не происходит gc, поэтому это работает.
<img width="660" alt="image" src="https://github.com/polis-vk/2023-nosql-lsm/assets/58121508/3081a134-50ef-4f2f-9a01-27836e06d054">

2023-10-23 18:49 UTC, y0f0 commented on src/main/java/ru/vk/itmo/pologovnikita/SSTable.java
> +            readPage = channel.map(FileChannel.MapMode.READ_ONLY, 0, fileSize, arena);
done

2023-10-28 19:51 UTC, AlexeyShik approved these changes
Подниму до 14 за исправление комментариев.

2023-10-28 19:51 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/pologovnikita/SSTable.java
>                      result = read();
Кажется, break потерял. Получается, что ты в любом случае пробежишь весь sstable, даже если ключ в самом начале.

2023-10-28 19:55 UTC, merged