Homework04
polis-vk/2023-nosql-lsm pull request #205
Opened 2023-10-27 22:18 UTC by MegaVerkruzo

2023-11-22 02:45 UTC, Dalvikk requested changes
Пока 17 баллов, в случае ошибки в compaction можем потерять данные и ухудшить производительность при рестарте

2023-11-22 02:45 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/grunskiialexey/Compaction.java
> +        deleteFilesAndInMemory(Files.readAllLines(indexFile, StandardCharsets.UTF_8), storagePath);
[критикал]
Правильно я понял, что общий пайплайн такой?
Предположим что на диске хранятся бд с версиями от 0 до n (по коду, как я понял, именно так и происходит)

1. Заполняем compaction данные в tmp файл -1
2. Удаляем старые данные 0-n и данные в памяти
3. Перемещаем файл -1 в файл 0
4. Пишем в indexFile что читать надо только из файла 0

Если да, то:
1. Предположим на 2 этапе при удалении случайного файла произойдет исключение (некоторые файлы уже удалились), или на 3 этапе (все файлы удалились). Тогда файлов на диске не будет, а compaction tmp файл мы никак не прочитаем (может есть recover из -1 файла в таком случае, не увидел)
2. Если пункт 4 отвалился, то в 0 файле (который самый старый) будут compaction данные (которые по факту дубликаты). В index файле будет инфа что надо читать с 0 до n. Фактически, вдвое больше данных и ущерб перфомансу.

2023-12-05 13:22 UTC, MegaVerkruzo commented
В общем, проблемы и правда были критикал, 
Что я поменял?
Так как ранее была проблема с -1, сейчас я сделал всё так. Каждый новый compaction или flush файл - будет либо 0, либо (последняя запись в index файле + 1), таким образом получается, что самое актуальное у нас хранится в конце. 

В compaction я сначала записываю в новый файл данные, когда дозаписал, изменяю index файл (через .tmp; тут если loadOrRecovery увидит .tmp файл, то подтянет его). Когда index файл поменялся, я удаляю .tmp файл. 

И уже после всех этих махинаций я могу спокойно удалять файлы

Также важная штука - в flush, и в compaction мы получаем название нового файла, но оно исходит из индекс файла, но если по факту будет такой файл (а он может быть в случай начала записи, и резкой поломке чего-то), то сработает TRUNCATE_EXISTING и всё хорошо

Да, сейчас если у нас компакшион сломался на моменте удаления файлов - то не удалившиеся файлы не удаляться никогда:)
Это можно поправить в loadOrRecovery

2023-12-05 14:20 UTC, MegaVerkruzo commented
Я сделал другое удаление файлов в Compaction, если у нас будет так, что compaction резко завершился в моменте удаления файлов, то он попробует ещё раз удалить файлы, которые не лежат в индекс файле

2023-12-26 01:04 UTC, Dalvikk approved these changes
25 баллов

2023-12-26 01:06 UTC, merged