Аленькова Юлия, магистратура "Распределенные веб-сервисы", 4 этап
polis-vk/2023-nosql-lsm pull request #209
Opened 2023-10-29 17:42 UTC by yulalenk

2023-11-11 11:35 UTC, atimofeyev requested changes

2023-11-13 22:12 UTC, atimofeyev approved these changes
5 баллов

2023-11-13 22:22 UTC, atimofeyev commented
поправьте компиляцию пожалуйста

2023-12-26 15:40 UTC, incubos commented
Проставлено в ведомость.

2023-12-26 15:40 UTC, closed without merging