Прокопьев Никита, Магистратура ИТМО "Распределенные веб-сервисы" 4 лабораторная
polis-vk/2023-nosql-lsm pull request #211
Opened 2023-10-30 09:14 UTC by Nikpro200125

2023-11-08 20:59 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/DaoImpl.java
>          lock.writeLock().lock();
в будущем этапе это уже будет нарушать требование - флаш не должен блокировать операции гет/пут

2023-11-08 20:59 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Files.deleteIfExists(path);
не жестко ли? а если ошиблись с расчетами индекса?

2023-11-08 20:59 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +             FileChannel channel = FileChannel.open(
только что сверху удалили а тут еще и транкейтим

2023-11-08 20:59 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Path path = config.basePath().resolve(DB_PREFIX + nextSSTable + DB_EXTENSION);
в целом опасно писать сразу в файл результирующий, он может не дописаться по какой-то причине и мы не узнаем о том что он битый, обычно в таком случае пишут в другой файл, а потом переименовывают

2023-11-08 21:02 UTC, atimofeyev requested changes

2023-11-08 21:02 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +            if (!Files.deleteIfExists(p)) {
в целом все очень шатко, попробуйте представить что в каждом из действии может случиться ошибка, хорошо бы это обнаружить, можно подсмотреть на то как делал Артем на семинаре

2023-11-08 23:01 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/DaoImpl.java
>          lock.writeLock().lock();
хорошо, учту при выполнении следующего этапа

2023-11-08 23:12 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +             FileChannel channel = FileChannel.open(
Согласен, чего-то одного достаточно, видимо была мысль, что буду проверять что файл уже существует и как-то это обрабатывать, а в итоге просто удаляю выше.

2023-11-08 23:22 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +            if (!Files.deleteIfExists(p)) {
Не совсем понимал при реализации насколько мы должны все обезопасить, поэтому реализовал так как есть, да действительно могут быть проблемы если у нас, например, пропадет файл или еще что-то случится, потом могут опять же возникнуть проблемы с генерацией индексов, в общем стоит наверное в целом переделать все что связано с хранением, чтобы это было более надежное хранилище.

2023-11-08 23:23 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Path path = config.basePath().resolve(DB_PREFIX + nextSSTable + DB_EXTENSION);
Видимо пропустил этот момент, учти в следующем этапе

2023-11-08 23:25 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Path path = config.basePath().resolve(DB_PREFIX + nextSSTable + DB_EXTENSION);
но тогда нужно еще будет где-то в работе системы проверять потом на наличие испорченных файлов, и что с ними нужно делать? просто сообщить об ошибке пользователю?

2023-11-08 23:31 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Files.deleteIfExists(path);
Была идея проверять, что файл существует, но тогда нужно было как-то это обрабатывать (менять название файла или вовсе бросать ошибку, так как по логике этого файла быть не должно), поэтому написал так в логике которую выбрал. учту в следующем этапе, чтобы как-то проверялось и обрабатывалась ситуации с наличием файлов, который по логике работы быть не должно.

2023-11-12 17:19 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Files.deleteIfExists(path);
лучше кидать ошибку если ожидается что-то а работает не так, это поможет в будущем избежать кучи проблем

2023-11-12 17:20 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Path path = config.basePath().resolve(DB_PREFIX + nextSSTable + DB_EXTENSION);
смотря какой файл испорчен, если испорчен файл который нужен для работы (SSTable), то надо кидать ошибку

2023-11-12 17:23 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +            if (!Files.deleteIfExists(p)) {
Да, мы пишем реальный сторадж, если есть какая-то вероятность сбоя - его надо учитывать. Промышленный код этим и отличается - там бОльшая часть кода - это обработака ошибок.

У нас конечно не настоящий промышленный, но надо быть к этому как можно ближе - в этом и суть всей лабы.

2023-11-12 19:55 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Path path = config.basePath().resolve(DB_PREFIX + nextSSTable + DB_EXTENSION);
Исправил, теперь храню файл index с названиями фалов (SStables), теперь файл добавляется в список файлов если он был записан.

2023-11-12 19:56 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +            if (!Files.deleteIfExists(p)) {
Исправил, теперь храню файл index с названиями файлов (SStables), и при удалении работаю именно с названиями из этого файла.

2023-11-12 20:00 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Files.deleteIfExists(path);
Исправил.

2023-11-12 20:00 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +             FileChannel channel = FileChannel.open(
Исправил.

2023-11-20 19:38 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/prokopyevnikita/Storage.java
> +        Path indexTmp = path.resolve(INDEX_TMP_FILE);
вот тут если мы упадем, следующее поднятие базы будет пустой

2023-11-20 19:41 UTC, atimofeyev approved these changes
15 баллов

2023-11-20 19:59 UTC, merged