Develop4
polis-vk/2023-nosql-lsm pull request #227
Opened 2023-11-01 04:09 UTC by PetyaVasya

Игорь Ковалев
ИТМО M3336

2023-11-22 17:55 UTC, Dalvikk requested changes
Пока 17 баллов, отказоустойчивость страдает

2023-11-22 17:55 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/kovalevigor/SSTableManager.java
> +                Files.copy(indexTmpPath, indexPath);
Можно же использовать move, который дешевле чем copy

2023-11-22 17:55 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/kovalevigor/SSTableManager.java
> +            final String sstableName = getNextSSTableName();
[критикал]

Так понимаю, общий пайплайн такой:
1. Пишем данные в tmp файлы
2. Удаляем предыдущие ssTables
3.  Перемещаем tmp файлы в реальную директорию

Если на этапе 3 произойдет исключение, то мы уже удалили предыдущие реальные файлы, и удалили tmp файл в finally{}
При перезапуске приложения, мы никак не восстановим эти данные, и даже ручками не найдем, они просто стерлись


P.S. Если решишь поменять пункт 2 и пункт 3 местами, учти что возникнет следующая проблема, которую надо будет решить:
1. Пишем данные в tmp файлы
2. Перемещаем tmp файлы в реальную директорию
3. Удаляем предыдущие ssTables

Если на этапе 3 произойдет исключение, но у нас в каталоге будет следующая ситуация: файлы с данными от 0 до n и компакшен файл n+1, в котором содержатся данные всех предыдущих файлов. При перезапуске приложения мы фактически в два раза больше всего будем читать, ущерб перфомансу

2023-11-23 21:39 UTC, PetyaVasya commented on src/main/java/ru/vk/itmo/kovalevigor/ShiftedIterator.java
> +    private boolean finished;
value = null -> не высчитывается

2023-12-05 17:55 UTC, PetyaVasya commented on src/main/java/ru/vk/itmo/kovalevigor/DaoImpl.java
> +        } catch (IOException e) {
Я бы с радостью бросил IOException, но так, к сожалению, нельзя
Буду возвращать null во всех случаях

2023-12-06 08:04 UTC, PetyaVasya commented on src/main/java/ru/vk/itmo/kovalevigor/SSTableManager.java
> +            final String sstableName = getNextSSTableName();
Теперь перемещаю файлы в tmp папку вместо удаления:
при ошибке - возвращаю обратно
при успехе - удаляю

Конечно, это все еще не закрывает все проблемы, например, если я не смогу вернуть файл обратно, то будет довольно грустно
И, наверное, тогда вместо бега по файлам в папке я хочу завести дополнительный файл со списком имен sstable. Однако, если я поймаю IOException пока я удаляю файлы, то оставшиеся останутся в забвении и никогда не будут удалены, т.к. я забуду всех их имена при перезапуске.
И в таком случае, наверное, хочется написать половину бонусного задания Durability (WAL), где будет сохранятся список файлов на удаление, чтобы при перезапуске бесконечно пытаться их удалить.

2023-12-26 02:08 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/kovalevigor/DaoImpl.java
> +        } catch (IOException e) {
Окей, в некоторых случаях вернуть частичные данные лучше чем ничего. Если бы мы делали код для прода, можно придумать враппер с флажком консистентности/неконсистентности.

2023-12-26 20:04 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/kovalevigor/SSTableManager.java
>              ssTables.add(SSTable.create(root, sstableName, arena));
При create внутри происходит маппинг в MemorySegment из файла, может упасть, а ssTables уже почистили. В рамках дз4 окей, так как все равно гарантируется что будет close() и работы с dao не будет. Просто безопаснее было бы сделать так, псевдокод:
```
newSSTable = SSTable.create(root, sstableName, arena)
newSSTables = new ArrayList<>().add(newSSTable)
ssTables = newSSTables
```

Думаю ты уже переделал в дз5 :)

2023-12-26 20:04 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/kovalevigor/SSTableManager.java
> +            final String sstableName = getNextSSTableName();
> Однако, если я поймаю IOException пока я удаляю файлы, то оставшиеся останутся в забвении и никогда не будут удалены, т.к. я забуду всех их имена при перезапуске

Думаю это не что то критически важное, все таки мы помним имена файлов которые корректные, значит можно пойти от обратного и почистить те имена, которые не корректные. Лично мне кажется лучше завести список имен, это избавит от множества move'ов и размышлений как сделать состояние стораджа максимально корректным в случае ошибок.

2023-12-26 20:15 UTC, Dalvikk approved these changes
25 баллов. В этом PR есть минорная проблема с возможными ошибками при move(), но они исправлены в PR с дз5, а то что я раньше не проверил дз4 -- моя проблема.

2023-12-26 20:37 UTC, Dalvikk commented
Сделаю reject PR чтобы не мержить конфликты, дз5 уже есть в мастере. У тебя 95 баллов и оценка 5, поздравляю!

2023-12-26 20:38 UTC, closed without merging