HW4 - Баженов Кирилл
polis-vk/2023-nosql-lsm pull request #230
Opened 2023-11-01 08:13 UTC by Kirill06344

2023-11-02 11:52 UTC, incubos commented
Напишите свою группу/институт, пожалуйста.

2023-11-19 13:54 UTC, lamtev requested changes
В решении есть довольно серьёзная проблемка. С ней могу поставить 15 баллов

2023-11-19 13:54 UTC, lamtev commented on src/main/java/ru/vk/itmo/bazhenovkirill/Storage.java
> +    private void compactData(Path ssTablePath, Collection<Entry<MemorySegment>> values) throws IOException {
По сигнатуре функции создаётся ощущение, что закомпактить нужно только `values`. Хотя в `values` только in-memory данные, а данные с диска подмёрживаются далее внутри функции

Восприятие усложняется, кмк

2023-11-19 13:54 UTC, lamtev commented on src/main/java/ru/vk/itmo/bazhenovkirill/Storage.java
> +        Files.write(indexFile,
Всё ли будет хорошо, если мы успеем удалить `existedFiles`, а потом сервер остановится, и мы не успеем обновить `indexFile` ?

2023-11-20 18:50 UTC, Kirill06344 commented on src/main/java/ru/vk/itmo/bazhenovkirill/Storage.java
> +    private void compactData(Path ssTablePath, Collection<Entry<MemorySegment>> values) throws IOException {
Осознал, передаю теперь в функцию сразу Iterable<Entry>, который состоит из всех значений(в memTable и sstable), поэтому теперь по должно восприниматься правильно

2023-11-20 18:51 UTC, Kirill06344 commented on src/main/java/ru/vk/itmo/bazhenovkirill/Storage.java
> +        Files.write(indexFile,
Согласен.Складываю все сначала во временный файл(уже скомпакченное), после чего удаляю все ненужное.При этом если что-то пойдет не так, то значения никуда не денутся.

2023-12-05 20:21 UTC, lamtev approved these changes
20 баллов

2023-12-05 20:21 UTC, merged