ДЗ 4 Шишигин Степан ITMO
polis-vk/2023-nosql-lsm pull request #231
Opened 2023-11-01 10:29 UTC by sshishigin

2023-11-07 20:08 UTC, atimofeyev requested changes

2023-11-07 20:08 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/shishiginstepan/BinarySearchSSTable.java
> +        Path sstPath = Path.of(path.toAbsolutePath() + "/sstable_" + id);
вот здесь опасно, мы пишем сразу в файлы с названием как у валидных таблиц, лучше писат ьсначала в какой-то тмп файл а потом переименовать. Чтобы в любом случае база работала только с правильно записанными файлами.

2023-11-07 20:08 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +        sstables.clear();
когда будете добавлять многопоточность - тут схватите проблем

2023-11-09 08:59 UTC, sshishigin commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +        while (data.hasNext()) {
Я думал об этом риске. Принял решение оставить именно такое решение, ввиду того, что в моем понимании MemorySegment не подгружает в память полностью те данные которые у нас лежат в файле, а делает это on-demand.

2023-11-09 08:59 UTC, sshishigin commented on src/main/java/ru/vk/itmo/shishiginstepan/BinarySearchSSTable.java
> +        Path sstPath = Path.of(path.toAbsolutePath() + "/sstable_" + id);
Спасибо, учту при разработке следующего этапа.

2023-11-09 08:59 UTC, sshishigin commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +                    path -> new BinarySearchSSTable(path, Arena.ofShared())).forEach(this.sstables::add);
Спасибо, учту при разработке следующего этапа.

2023-11-09 09:03 UTC, sshishigin commented
@atimofeyev Не очень понял. Увидел, что вы не просто комментарии оставили, а запросили изменения. Я могу поправить то что вы отметили прямо в этом ПР ?

2023-11-11 13:41 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +        while (data.hasNext()) {
так тут дело не в MemorySegment а в ArrayList
Он то выделяет столько памяти сколько надо

2023-11-11 13:43 UTC, atimofeyev commented
> @atimofeyev Не очень понял. Увидел, что вы не просто комментарии оставили, а запросили изменения. Я могу поправить то что вы отметили прямо в этом ПР ?

да, если вы исправляете комментарии то бал будет выше результирующий
т/е/ например за то что вы собираете все в ArrayList сразу сбавляется 50 процентов баллов, если поправите, то будет просто небольшой минус за изначальную ошибку

2023-11-13 22:08 UTC, atimofeyev approved these changes
10 баллов

2023-11-13 22:12 UTC, merged