Новичков Андрей М3232 ФИТиП, HW4
polis-vk/2023-nosql-lsm pull request #245
Opened 2023-11-01 19:54 UTC by croil

2023-11-22 09:53 UTC, Dalvikk requested changes
Пока 15 баллов

2023-11-22 09:53 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/novichkovandrew/table/MMapTableWriter.java
> +    private final FileChannel channel;
channel можно не хранить и закрывать при инициализации в try-with-recoures.
Замапленные сегменты через channel.map() останутся доступны, несмотря на то что channel закрылся


https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/commit/man2/mmap.2?id=3ee0a7f07ed1bd607e598bc4477af0dea5db4084

2023-11-22 09:53 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/novichkovandrew/table/MMapTableWriter.java
> +                channel.transferTo(indexHandle.offset(), indexOffset, channel);
А такой случай возможен, когда indexHandle.offset() > dataOffset true? Не понял где хранятся индексы, в начале файла или в конце, и зачем нужен transferTo

2023-11-22 09:53 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/novichkovandrew/table/MMapTableWriter.java
> +        this.arena = Arena.ofShared();
Арена может быть confined, так как мы вызываем Writer и закрываем его в рамках одного потока

2023-11-22 09:53 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/novichkovandrew/table/MMapTableWriter.java
> +            channel.truncate(indexOffset + Footer.FOOTER_SIZE);
Зачем нужен truncate? Выглядит небезопасно, мало ли что то обрежется и нужно ли

2023-11-22 09:53 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/novichkovandrew/dao/PersistentDao.java
> +        //TableBuilder
Давай добавим проверку нужно ли что то флашить если данных в памяти нет

2023-11-22 09:53 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/novichkovandrew/dao/PersistentDao.java
> +        Files.move(compactPath, tablePath);
Если тут произойдет исключение, то все старые таблицы уже удалены, а из compactPath рекаверинга нет.

2023-11-22 09:53 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/novichkovandrew/dao/PersistentDao.java
> +        Path compactPath = path.resolve("temp.txt");
Давай добавим проверку нужно ли что то компактить (например файлов на диске нет или он один + данных в in memory dao нет)

2023-11-22 10:57 UTC, croil commented on src/main/java/ru/vk/itmo/novichkovandrew/table/MMapTableWriter.java
> +                channel.transferTo(indexHandle.offset(), indexOffset, channel);
Да. Возможен. Чтобы записывать данные, мапится кусок для данных затем для индексов. Но в реальности данных может записаться меньше(выкидываем tombstone или старые значения например). Поэтому между смапленным куском данных и смапленным куском индексов образуется дыра. Из-за этого я делаю channel.transferTo(indexHandle.offset(), indexOffset, channel) - это я индексы переношу выше по файлу. Ну и truncate из комментария ниже просто обрезает те ненужные байты с конца. 
В будущем планируется сделать буферизированную запись, делая mmap по 1 Мб вместо того чтобы мапить весь кусок для записи данных. Я проверял, это сильно меньше будет грузить оперативы и так делают дядьки из гугла в leveldb. Однако тогда нельзя будет мапить место для индексов. Потому что transferTо. Поэтому планируется хранить индекс в памяти, раз у нас теперь flush делается регулярно, это не будет занимать много памяти.

2023-11-22 18:03 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/novichkovandrew/table/MMapTableWriter.java
> +            channel.truncate(indexOffset + Footer.FOOTER_SIZE);
Прочитал коммент выше и понял

2023-12-26 20:40 UTC, Dalvikk commented
Прошло много времени, фиксов комментов не было. Оставлю 15 баллов и закрою PR, сейчас у тебя в сумме 55, что хватает на 3.

2023-12-26 20:40 UTC, closed without merging