ИТМО ФИТиП, Пологов Никита hw4
polis-vk/2023-nosql-lsm pull request #250
Opened 2023-11-06 16:08 UTC by y0f0

Перенос дедлайна согласован до 8.11. За основу взято решение hw3 из семинара.

2023-11-22 04:32 UTC, Dalvikk requested changes
пока 18 баллов, есть один момент с отказоустойчивостью

2023-11-22 04:32 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +@SuppressWarnings("PMD.TooManyStaticImports")
[минор, код стайл]
Статик импорты лучше обходить стороной и не использовать

2023-11-22 04:32 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +            DiskStorage.save(compactionalPath, entries); //save all in compact file
А если данных в in memory dao нет, а файл на диске всего один (поэтому hasNext() и вернул true)?

2023-11-22 04:32 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +        try (var dirStream = Files.walk(path)) {
А директории зачем обходить? По идее, раз это с референсного решения, в пути хранятся только файлы. Мало ли что произойдет, но в целом не критично

2023-11-22 04:32 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +        Files.move(compactionalPath, path, StandardCopyOption.ATOMIC_MOVE); //move from compact to new main file
[критично]
Если тут произойдет исключение, то старые файлы мы потеряли и при dao.reopen() не прочитаем ничего из path

2023-12-21 21:46 UTC, y0f0 commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +        Files.move(compactionalPath, path, StandardCopyOption.ATOMIC_MOVE); //move from compact to new main file
если ты про 199 строчку, то поправил и добавил move в finally, а если про 200 то тут я плохо понимаю как это захендлить

2023-12-21 22:13 UTC, y0f0 commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +            DiskStorage.save(compactionalPath, entries); //save all in compact file
done

2023-12-21 22:14 UTC, y0f0 commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +@SuppressWarnings("PMD.TooManyStaticImports")
да сорри, как то лень было рефакторить сделал как проще

2023-12-28 04:46 UTC, Dalvikk reviewed
Проблемы исправлены, появилась новая с возможным ущербом перфомансу. Поставлю 21 балл, мержить изменения не буду, а то сломает код других студентов.

2023-12-28 04:46 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +        Path compactionalData = compactionalDirectory.resolve(newIndex);
Тут происходит поиск файла с компакшен данными.
Когда мы делали save(compactionalDirectory, entries), мы предполагали что там нет других файлов и запишется файл с индексом 0. А потом мы ищем файл по newIndex, который либо 0, либо pathIndexes.get(0) (который как понимаю тоже должен быть 0 в рамках контрактов нашей dao).

Предположим вызвали compact(). Мы успели сделать compact() в compaction директорию, но при move() произошла ошибка. Тогда у нас в compaction директории остался какой то compaction0 файл.

После опять поработали с dao, изменили всякие entry и опять вызываем compact().
В compaction директорию попадет второй файл с индексом compaction1.
Когда мы будем считать newIndex мы посчитаем 0.
И при втором compact() будет делать move() compaction0 файла, а не compaction1 как должно.

Как можно пофиксить: можно добавить/изменить метод save, чтобы он возвращал индекс добавленного файла. И тут уже детать compactionalDirectory.resolve(compactionIndex);

2023-12-28 04:46 UTC, Dalvikk commented on src/main/java/ru/vk/itmo/pologovnikita/DiskStorage.java
> +        Path compactionalIndexesFile = getIndexFile(compactionalDirectory);
В чем может быть проблема если бы упадем на этом этапе: предположим на диске хранятся индексы 0, 1, 2 и вызвали compact(). У них у всех есть какой то key1, которому присвоено разное значение. И есть key1 в памяти, самый свежий.

1. Записали данные с диска и памяти в compaction директорию, получился 1 файл с индексом 0.
2. Переместили индекс 0 из compaction директории в data директорию.
3. Упали на 3 этапе, замене индекс файла.
4. Дао перезапустилось (работа окончена либо клиент сам вызвал close и open)

Что получится: в директории лежат 0, 1, 2 файлы, причем 0 файл это компакшен файл который самый свежий (но считается самым старым)
1. Могут быть ошибки что мы возвращаем неверное значение key1, так как поиск идет начиная с 2 файла, а самые свежие данные в 0 (он также содержит данные из памяти, поэтому самый свежий). Хотя возможно их не будет, так как при close() мы делаем flush(), и запишется условный четвертвый файл с индексом 3, но само по себе состояние неконсистентное и неприятное.
2. Ущерб перфомансу. Данные фактически дублируются, мы лишний раз будем проходить по 2 и 1 и 0 файлу, хотя достаточно только в 0.

Возможный способ исправить:
Делать индекс compaction файла n + 1, если компактим n данных. Тогда если мы упадем на замене индекс файла, в директории будет либо {0, n} либо {n + 1} и таких эффектов не будет. Придется отказаться от контракта что первый индекс файл начинается с 0.

2023-12-28 04:49 UTC, closed without merging