HW5 Александра Дягай, Политех
polis-vk/2023-nosql-lsm pull request #265
Opened 2023-11-21 13:09 UTC by fo-xi

2023-12-03 19:46 UTC, Marashov-Alexander requested changes
14 / 30 баллов
-1 балл за использование всего компаратора лишь для определения равенства
-1 балл за лишний ArrayList при get, который тут же удаляется 
-1 балл за смешение в кучу приватный, финальных, статических полей и несооветствие нейминга у последних
-3 балла за отсутствие volitile у переменной, которая меняется в разных потоках
-3 балла за отсутствие обратной совместимости с дефолтным конструктором: если создать через него, то Storage превратится в тыкву
-3 балла за отсутствие from-to по flushingMapIterator
-3 балла за использование переменных state не под блокировкой на чтение  
-1 балл за создание неиспользуемых ConcurrentSkipListMap в state в поле flushingDataStorage

Ожидаю исправлений для повторной проверки :)

2023-12-11 07:08 UTC, Marashov-Alexander commented
@fo-xi , планируются ли исправления?

2023-12-11 07:40 UTC, fo-xi commented
постараюсь исправить замечания до конца этой недели

2023-12-20 16:24 UTC, Marashov-Alexander commented
(Исправления не предоставлены, закрываю PR)

2023-12-20 16:32 UTC, Marashov-Alexander approved these changes

2023-12-20 16:33 UTC, merged