ITMO, Khadyrov Almasgali, M3335, H/W 1
polis-vk/2023-nosql-lsm pull request #27
Opened 2023-09-25 18:50 UTC by Almasgali

2023-09-27 22:49 UTC, AlexeyShik requested changes
Нужно поправить компаратор

2023-09-27 22:49 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/khadyrovalmasgali/InMemoryDao.java
> +        for (long i = 0, j = 0; i < size1 && j < size2; ++i, ++j) {
Много лишних операций `get`. У `MemorySegment` есть метод, который позволяет найти позицию отличия от другого `MemorySegment`, он содержит достаточно оптимизаций, поэтому будет работать быстрее чем такой цикл. Следует найти и поиспользовать этот метод.
А еще ведь `i` и `j` всегда одинаковые значения принимают, получается, `j` лишняя переменная - это лишняя аллокация на стеке (хоть и дешевле чем в куче, но все равно) и лишние инкременты.

2023-09-27 22:49 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/khadyrovalmasgali/InMemoryDao.java
> +    private final ConcurrentSkipListMap<MemorySegment,
Лучше в качестве типа для `data` использовать интерфейс, а не реализацию.
С одной стороны для переменной можно использовать тип `SortedMap` как наиболее общий интерфейс. С другой стороны интерфейс `ConcurrentNavigableMap` ярко подчеркивает многопоточность кода, что в крупном проекте поможет другим разработчикам, которые будут читать / модифицировать ваш код, быстрее в нем разобраться. Можете выбрать любой интерфейс.

2023-09-28 11:03 UTC, Almasgali commented on src/main/java/ru/vk/itmo/khadyrovalmasgali/InMemoryDao.java
> +        for (long i = 0, j = 0; i < size1 && j < size2; ++i, ++j) {
поправил

2023-09-28 11:03 UTC, Almasgali commented on src/main/java/ru/vk/itmo/khadyrovalmasgali/InMemoryDao.java
> +    private final ConcurrentSkipListMap<MemorySegment,
поправил

2023-10-02 15:12 UTC, AlexeyShik approved these changes
Все хорошо, 9 баллов

2023-10-02 15:41 UTC, merged