Bonus Чеботин Александр (ITMO DWS)
polis-vk/2023-nosql-lsm pull request #302
Opened 2023-12-14 04:18 UTC by axothy

Реализована поддержка фильтров Блюма для SSTables. 

В качестве хеш-функции была взята 64-битная версия Murmur3 hash.

2023-12-27 12:45 UTC, incubos commented
Не проходит один тест. Есть множество замечаний от CodeClimate.

2023-12-27 13:26 UTC, incubos requested changes
Есть ряд вопросов и замечаний. Бонусные фичи предполагают разработку дополнительного набора тестов/бенчмарков, которые показывают корректность и/или профит от бонусной фичи. Добавите бенчмарков, которые показывают, что `get()` стал работать быстрее, благодаря фильтру Блума?

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/MurmurHash.java
> + */
:+1:

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/MurmurHash.java
> +            long k1 = getBlock(key, offset, i * 2 + 0);
```suggestion
            long k1 = getBlock(key, offset, i * 2);
```

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/MurmurHash.java
> +        int i8 = index << 3;
Почему умножаем именно на `8`? Комментарии были бы не лишними.

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/MurmurHash.java
> +        return ((long) key.get(ValueLayout.JAVA_BYTE, blockOffset + 0) & 0xff)
Нельзя ли извлечь из сегмента 8 байт как `long` более эффективным способом?

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTableIterator.java
> +        long keysOffset = sstable.get(ValueLayout.JAVA_LONG_UNALIGNED, offset);
`keysOffset` не очень удачное название переменной, согласны?

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTableUtils.java
> +        while (low < high - 1) {
Почему код из `binarySearch()` выше дублируется здесь?

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTableUtils.java
> +    private static Entry<MemorySegment> get(MemorySegment sstable, long index, final long afterBloomFilterOffset) {
Почему один параметр с `final`, а остальные -- без?

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTableUtils.java
>  public final class SSTableUtils {
Здесь или где-то ещё не хватает описания вашего бинарного формата с фильтром Блума -- уследить за модификацией смещений довольно трудно.

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTablesStorage.java
> +    // |key2 offset| ... |key_n offset|key1Size|key1|value1Size|value1| ...
- Непонятны размеры полей
- Чем `bf length` отличается от `bf bit size`?

2023-12-27 13:26 UTC, incubos commented on src/main/java/ru/vk/itmo/chebotinalexandr/NotOnlyInMemoryDao.java
> +        long newBloomFilterLength = BloomFilter.divide(entryCount, Long.SIZE);
В оригинальном применении фильтров Блума к LSM, битовый размер фильтра вычисляется как функция от количества элементов (entry) и допустимого значения false positive -- можем повторить?

2023-12-27 13:33 UTC, axothy commented
> Есть ряд вопросов и замечаний. Бонусные фичи предполагают разработку дополнительного набора тестов/бенчмарков, которые показывают корректность и/или профит от бонусной фичи. Добавите бенчмарков, которые показывают, что `get()` стал работать быстрее, благодаря фильтру Блума?

Да, хорошо, добавлю. Есть еще идея с оценкой процента false positive фильтра.

2024-01-01 17:50 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/BloomFilter.java
> +        long rem = p - q * div;
Да, это тоже самое, сделал просто p % q

2024-01-01 17:51 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/BloomFilter.java
> +    public static long divide(long p, long q) {
Функция деления long с округлением в большую сторону (используется для деления количества элементов в sstable на 64). Внес комментарии к вычислениям

2024-01-01 17:52 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/BloomFilter.java
> +        boolean increment = sgn > 0;
Это скорее обобщенная реализация деления чисел p на q с округлением. Убрал лишний код, для фильтра Блюма достаточно, на самом деле, предположения о том что p и q - оба положительны. Метод divide сделал private. Логику вычисления размера битового массива инкапсулировал. 

Выражение `signum = 1 | (int) ((p ^ q) >> (Long.SIZE - 1))` возвращало 1 если p и q одного знака, иначе -1. Далее это использовалось для округления в большую сторону, таким образом делая реализацию divide рабочей и для неотрицательных чисел тоже.

2024-01-01 17:58 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/BloomFilter.java
> +    private static final int LONG_ADDRESSABLE_BITS = 6;
Это степень двойки, 2^6 = 64. Поэтому мы всегда берем первые m = 6 бит от хеша для фильтра с 2^m бакетов, интерпретируя это в качестве индекса для доступа к нужному биту в массиве

2024-01-01 17:58 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/BloomFilter.java
> +        int longIndex = (int) (bitIndex >>> LONG_ADDRESSABLE_BITS); //this is an arrayIndex
Исправил

2024-01-01 17:59 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/BloomFilter.java
> +        long bitOffset = 4L * Long.BYTES + longIndex * Long.BYTES;
Да, исправил это

2024-01-01 17:59 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/BloomFilter.java
> +        long bitOffset = 4L * Long.BYTES + longIndex * Long.BYTES;
Теперь исправлено

2024-01-01 17:59 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/BloomFilter.java
> +        long bitOffset = 4L * Long.BYTES + longIndex * Long.BYTES;
Убрал дублирование

2024-01-01 18:00 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/MurmurHash.java
> +        int i8 = index << 3;
У нас блоки 16-байтовые, поэтому индекс умножается на 16 (он при передаче аргумента уже умножается на 2 и в теле методе домножается еще на 8). Переписал метод чтобы он был более понятным. Добавил комментарии

2024-01-01 18:02 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/MurmurHash.java
> +        return ((long) key.get(ValueLayout.JAVA_BYTE, blockOffset + 0) & 0xff)
Попробовал по-другому извлечь через метод getLong у ByteBuffer. Допустимо ли так или все еще есть более эффективный способ?

2024-01-01 18:02 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTableIterator.java
> +        long keysOffset = sstable.get(ValueLayout.JAVA_LONG_UNALIGNED, offset);
Да, согласен, изменил переменную

2024-01-01 18:03 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTableUtils.java
> +    private static Entry<MemorySegment> get(MemorySegment sstable, long index, final long afterBloomFilterOffset) {
Исправлено

2024-01-01 18:05 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/SSTablesStorage.java
> +    // |key2 offset| ... |key_n offset|key1Size|key1|value1Size|value1| ...
`bf length` это длина битового массива, а `bf bit size` это просто `bf length * 64`. На самом деле `bf bit size `хранить в sstable необязательно, достаточно просто bf length.  Изменил формат таблицы, убрав `bf bit size`

2024-01-01 18:08 UTC, axothy commented on src/main/java/ru/vk/itmo/chebotinalexandr/NotOnlyInMemoryDao.java
> +        long newBloomFilterLength = BloomFilter.divide(entryCount, Long.SIZE);
Да, можно - теперь передается из Config параметр false-positive probability (0.0 < fpp < 1.0). Проверил эмпирически на тестовых данных, этот параметр в действительности с небольшой погрешностью совпадает с задаваемым fpp

2024-01-01 18:17 UTC, axothy commented
@incubos 

Провел исследование при помощи написанных бенчмарков. 

1) Я менял постоянно количество SSTable и каждый раз оценивал время выполнения метода get() для 50 000 entries. 
На первом рисунке виден график зависимости времени выполнения операции get() от количества таблиц на диске, откуда видно, что с увеличением таблиц растет время get(), при этом получено очень хорошее ускорение с фильтром Блюма (на данном графике параметр false-positive probability фиксировался и был равным 0.03)

<img width="1593" alt="time(sstables)" src="https://github.com/polis-vk/2023-nosql-lsm/assets/61747868/92adf248-9420-476d-96f1-e745cb809e65">

2) На втором рисунке привел график зависимости времени выполнения get() от false-positive probability. В данном исследовании количество таблиц было фиксировано, менялся лишь параметр fpp. Видно, что с уменьшением данного параметра, время операции get() с фильтром уменьшается, а при fpp близком к единице время выполнения стремится к времени выполнения get() без фильтра Блюма. Это вполне логично, так и должно быть. Кривая, соответствующая времени операции get() без фильтра Блюма постоянна, так как в данном графике менялся лишь fpp. Немонотонность кривой объясняется шумом при бенчмарках.

<img width="1577" alt="time(fpp)" src="https://github.com/polis-vk/2023-nosql-lsm/assets/61747868/e7087c4e-194b-4c37-9db0-2ccd44d03a91">

2024-01-01 18:18 UTC, axothy commented
Тест теперь проходит, осталось привести код в порядок чтобы codeclimate не ругался.

2024-01-09 09:22 UTC, incubos commented
28 баллов. Спасибо за работу!

2024-01-09 09:22 UTC, closed without merging