Пелогейко Макар Андреевич, ИТМО DWS
polis-vk/2023-nosql-lsm pull request #36
Opened 2023-09-26 03:54 UTC by makar-pelogeiko

[Home work 1]

- task solution

2023-09-28 20:16 UTC, atimofeyev requested changes

2023-09-28 20:16 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/pelogeikomakar/MemorySegmentComparator.java
> +            byte second = o2.get(ValueLayout.JAVA_BYTE, offset);
Лучше воспользоваться mistmach-em
Такой вариант точно будет работать медленнее в общем случае

2023-10-01 17:33 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/pelogeikomakar/MemorySegmentComparator.java
> +        if (first != second) {
очень странная конструкция, можно просто 
return first - second

2023-10-01 17:39 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/pelogeikomakar/MemorySegmentComparator.java
> +        if (o1Size == 0 && o2Size == 0) {
я бы не делал эти проверки, большинство строк будет не пустые, и эти проверки будут лишними

2023-10-01 17:41 UTC, atimofeyev approved these changes

2023-10-01 17:42 UTC, atimofeyev commented
9 баллов (-1 балл за бесполезные if-ы)

2023-10-02 15:33 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/pelogeikomakar/MemorySegmentComparator.java
> +        if (first != second) {
Согласен, изначально сделал это для наглядности.

Но потом решил оставить для избегания автоматического приведения типов: byte в int переводится нормально, но вот long в int может быть переведен с изменением знака: ```For instance, 2147483648 would be represented as -2147483648 ``` (https://stackoverflow.com/questions/4355303/how-can-i-convert-a-long-to-int-in-java)

2023-10-08 06:22 UTC, merged