Implemented classes DaoFactoryImpl and InMemoryDaoImpl
polis-vk/2023-nosql-lsm pull request #40
Opened 2023-09-26 12:05 UTC by ALTV2

2023-09-28 13:43 UTC, atimofeyev approved these changes

2023-09-28 13:43 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tveritinalexandr/DaoFactoryImpl.java
> +        return memorySegment == null ? null : new String(memorySegment.asByteBuffer().array(), StandardCharsets.UTF_8);
а почему тут не просто asArray()?

2023-10-01 17:48 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tveritinalexandr/DaoFactoryImpl.java
> +        return memorySegment == null ? null : new String(memorySegment.asByteBuffer().array(), StandardCharsets.UTF_8);
конструкция memorySegment.asByteBuffer().array() не сработает для non heap byte buffer

2023-10-01 17:50 UTC, atimofeyev commented
10 баллов

2023-10-08 06:53 UTC, atimofeyev requested changes

2023-10-08 06:53 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/tveritinalexandr/SSTableLoader.java
> +        SortedMap<MemorySegment, Entry<MemorySegment>> map = new ConcurrentSkipListMap<>(comparator);
зачем мы читаем все в мапу? она же потом не используется

2023-10-08 06:53 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/tveritinalexandr/SSTableLoader.java
> +        try (FileChannel channel = FileChannel.open(ssTableFilePath, StandardOpenOption.READ)) {
каждый раз открывать канал - слишком дорого, идея MemorySegment чтобы один раза замапить файл и потом просто бегать по памяти

2023-10-08 06:54 UTC, atimofeyev commented
некрректное решение, тесты падают

2023-10-09 10:53 UTC, vladimir-bf commented
@ALTV2 вам нужно создать отдельный пулл реквест для второго задания

2023-10-09 17:25 UTC, ALTV2 commented on src/main/java/ru/vk/itmo/tveritinalexandr/SSTableLoader.java
> +        SortedMap<MemorySegment, Entry<MemorySegment>> map = new ConcurrentSkipListMap<>(comparator);
Скорее всего,  я неверно понял тз к данному этапу. Предполагал, что при старте БД мы должны заполнять mem Table из сохраненной SST для увеличения скорости доступа.

2023-10-09 17:29 UTC, ALTV2 commented on src/main/java/ru/vk/itmo/tveritinalexandr/SSTableLoader.java
> +        try (FileChannel channel = FileChannel.open(ssTableFilePath, StandardOpenOption.READ)) {
Да, теперь уже понимаю) Просто оставил слишком мало времени на выполнение работы.

2023-10-22 20:08 UTC, atimofeyev commented
0 баллов

2023-11-04 22:40 UTC, closed without merging