HW2 Кобыжев Александр, Политех ИВТ
polis-vk/2023-nosql-lsm pull request #83
Opened 2023-10-01 20:03 UTC by alexnevskiy

Реализован persistence storage

Кобыжев Александр, магистратура СПбПУ, ИВТ

2023-10-18 12:14 UTC, lamtev requested changes
Решение оценивается в 7 баллов из 15. Балл снимается суммарно за все минорные проблемы. И половина - за мажорную. Вот её давайте поправим ASAP, и баллы будут пересчитаны

2023-10-18 12:14 UTC, lamtev commented on src/main/java/ru/vk/itmo/kobyzhevaleksandr/InMemoryDao.java
> +        this.config = new Config(Path.of(""));
[minor] Хорошей практикой является реализовать перегрузки конструкторов через соседние. Выглядит так, что тут подошло бы `this(Path.of(""));`

2023-10-18 12:14 UTC, lamtev commented on src/main/java/ru/vk/itmo/kobyzhevaleksandr/InMemoryDao.java
>  public class InMemoryDao implements Dao<MemorySegment, Entry<MemorySegment>> {
[medium] Возможно, стоило переименовать класс или новую реализацию делать отдельным классом. Текущее название для текущей реализации вводит в заблуждение

2023-10-18 19:00 UTC, alexnevskiy commented on src/main/java/ru/vk/itmo/kobyzhevaleksandr/InMemoryDao.java
> +    private long writeSegmentToMappedTableFile(MemorySegment mappedTableFile, MemorySegment segment, long offset) {
Исправил, также сделал `static` метод `mapFile()`

2023-10-18 19:05 UTC, alexnevskiy commented on src/main/java/ru/vk/itmo/kobyzhevaleksandr/InMemoryDao.java
> +        this.config = new Config(Path.of(""));
Вообще у меня было реализовано без перегрузки по причине пробрасываемого `IOException`, так как конструктор без аргументов вызывается в тестах, где данное исключение не пробрасывается. Сейчас исключение ловится в отдельном блоке `catch`, что позволило избавиться от `throws IOException`.

2023-10-19 09:34 UTC, lamtev approved these changes
14 баллов

2023-10-19 09:36 UTC, merged