ДЗ stage 2 Шишигин Степан ТИНТ ИТМО
polis-vk/2023-nosql-lsm pull request #87
Opened 2023-10-02 11:09 UTC by sshishigin

2023-10-08 16:52 UTC, incubos commented
Нужно откатить изменения не в вашем package.

2023-10-08 16:52 UTC, incubos commented
Тест не проходит и указывает на баги.

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/InMemDaoImpl.java
> +    private final ConcurrentSkipListMap<MemorySegment, Entry<MemorySegment>> memStorage = new ConcurrentSkipListMap<>(
Почему в качестве типа поля используется конкретная реализация `ConcurrentSkipListMap`, а не абстрактный интерфейс `ConcurrentNavigableMap` или даже `NavigableMap`?

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/InMemDaoImpl.java
> +        persistentStorage = new PersistentStorage(this.basePath);
Выше с `this.`, а здесь -- без.

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/InMemDaoImpl.java
> +        persistentStorage = new PersistentStorage(this.basePath);
```suggestion
        this.persistentStorage = new PersistentStorage(this.basePath);
```

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/InMemDaoImpl.java
>      public Iterator<Entry<MemorySegment>> get(MemorySegment from, MemorySegment to) {
На этапе 2 range-запросов нет, а текущая реализация "смотрит" только в memtable.

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +    // TODO заменить на интерфейс сстейбл
Это `TODO` для следующего этапа?

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +            dataSize += entry.value().byteSize() + entry.key().byteSize() + 16;
Так было бы чуть понятнее:
```suggestion
            dataSize += Long.BYTES + entry.value().byteSize() + Long.BYTES + entry.key().byteSize();
```

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +            dataSize += entry.value().byteSize() + entry.key().byteSize() + 16;
Абстракции потекли: мы в `TODO` выше хотели некий абстрактный интерфейс для SSTable, а тут мы считаем размер чистых данных с накладными расходами на `long`-размеры ключей и значений, т.е. что-то знаем о формате. Может быть, писать не через `mmap`, а через `FileChannel`, и ограничиться `data.iterator()` -- это было бы максимально универсально. Либо передавать не `Iterator`, а `NavigableMap`.

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +        return ssTableResult == null ? null : new Entry<>() {
Сложная конструкция с тернарным оператором и анонимным классом, который ещё и ссылку на `PersistentStorage` будет держать. Можно проще?

2023-10-08 17:41 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/PersistentStorage.java
> +        return ssTableResult == null ? null : new Entry<>() {
Сложная конструкция с тернарным оператором и анонимным классом, который ещё и ссылку на `PersistentStorage` будет держать. Можно проще?

2023-10-08 17:54 UTC, incubos requested changes
Нужно починить баг, из-за которого не проходят тесты -- получите часть баллов.

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +    private long size;
Нужно ли это поле? Почему оно не `final`?

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +            if (!Files.exists(basePath)) {
Это не требуется. Пусть пользователь сам создаёт каталог, раз его указал.

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +        sstPath = Path.of(basePath.toAbsolutePath() + "/sstable");
Такие литералы должны быть константами в классе.

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +                Files.createFile(sstPath);
Зачем всегда создавать файл? Вдруг никто и не собирается вызывать `writeEntries()`?

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +            var file = fileChannel.map(FileChannel.MapMode.READ_WRITE, 0, dataSize, Arena.ofConfined());
```suggestion
            var segment = fileChannel.map(FileChannel.MapMode.READ_WRITE, 0, dataSize, Arena.ofConfined());
```

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +            var file = fileChannel.map(FileChannel.MapMode.READ_WRITE, 0, dataSize, Arena.ofConfined());
Арена не закрывается, поэтому сегмент будет заmmap()лен до прихода GC, верно?

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +        try (var fileChannel = FileChannel.open(sstPath, StandardOpenOption.READ, StandardOpenOption.WRITE)) {
Открытие файла это не дешёвая операция и на каждый вызов `get()` так делать не очень хорошая идея.

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +        try (var fileChannel = FileChannel.open(sstPath, StandardOpenOption.READ, StandardOpenOption.WRITE)) {
Зачем тут `StandardOpenOption.WRITE`?

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +            var file = fileChannel.map(FileChannel.MapMode.READ_ONLY, 0, this.size, Arena.ofConfined());
Арена не закрывается и сегмент останется жить до прихода GC, верно?

2023-10-08 17:54 UTC, incubos commented on src/main/java/ru/vk/itmo/shishiginstepan/SimpleSSTable.java
> +                offset += keySize;
Это мы делаем и внутри `if`, поэтому можно поставить перед `if`.

2023-10-10 11:32 UTC, sshishigin commented on src/test/java/ru/vk/itmo/DaoTest.java
> +@Timeout(5)
Ошибся, менял во время дебага, закомитил случайно

2023-10-10 21:04 UTC, sshishigin commented
Большое спасибо за внимательное и обширное ревью. Все отмеченные ошибки будут исправлены к следующему этапу. ЧТо касается бага, из-за которого не проходили тесты - я его нашел и починил.

2023-10-10 21:06 UTC, incubos requested changes

2023-10-10 21:06 UTC, incubos commented on src/test/java/ru/vk/itmo/DaoTest.java
> +@Timeout(5)
Откатите, пожалуйста -- с этим изменением нельзя мёрджить.

2023-10-11 08:42 UTC, sshishigin commented on src/main/java/ru/vk/itmo/plyasovklimentii/InMemoryDao.java
> +            return storage.subMap(from, true, to, false).sequencedValues().iterator();
Готово

2023-10-11 09:57 UTC, incubos commented
5 баллов.

2023-10-11 09:57 UTC, incubos approved these changes

2023-10-11 09:57 UTC, merged