Свистухин Андрей, Магистратура ИТМО "Распределенные веб-сервисы", задание 2
polis-vk/2023-nosql-lsm pull request #92
Opened 2023-10-03 00:53 UTC by stormrvge

2023-10-03 01:06 UTC, stormrvge commented
Сорри, отбренчевался от ветки с первой лабы, подтянул старые коммиты.

Если вкратце, я разбил value блоки на фрагменты определенного размера, чтобы сразу знать на сколько прыгать вперед по памяти, а не читать value ключа, который нам не нужен.

2023-10-09 20:46 UTC, atimofeyev requested changes

2023-10-09 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/svistukhinandrey/PersistentDao.java
> +        if (storage.containsKey(key)) {
в позитивном сценарии мы делаем два гета
storage.containsKey(key) и storage.get(key)
лучше оставить один

2023-10-09 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +            data = dataFileChannel.map(FileChannel.MapMode.READ_ONLY, 0, dataFileChannel.size(), Arena.global());
С глобальной ареной мы израсходуем всю память, сегменты не деаллоцируются в ней

2023-10-09 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +            byte keySize = data.get(ValueLayout.JAVA_BYTE, pos++);
очень мало байта на размер ключа

2023-10-09 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +            long fragmentation = ((valueSize + KEY_BLOCK_SIZE - 1) / KEY_BLOCK_SIZE) * KEY_BLOCK_SIZE;
сколько получилось сэкономить от этой манипуляции?

2023-10-10 00:19 UTC, stormrvge commented on src/main/java/ru/vk/itmo/svistukhinandrey/PersistentDao.java
> +        if (storage.containsKey(key)) {
сделать get, и если достали null, то ключ не найден?
да, что-то упустил этот момент

2023-10-10 00:20 UTC, stormrvge commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +            data = dataFileChannel.map(FileChannel.MapMode.READ_ONLY, 0, dataFileChannel.size(), Arena.global());
на лекции уже узнал, но исправить нельзя было
я бегло прочитал, увидел что память не освобождается после того, как мы перестаем его использовать, и я подумал, что это как раз то, что нужно, так как файл мы оставляем на диске.
в следующий раз буду читать внимательнее))

2023-10-10 00:25 UTC, stormrvge commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +            long fragmentation = ((valueSize + KEY_BLOCK_SIZE - 1) / KEY_BLOCK_SIZE) * KEY_BLOCK_SIZE;
на самом деле, эту фрагментацию я хотел выпилить, так как в целом, она ничего не дает
я рассматривал два варианта того как это сделать, и в итоге один наложился на другой, и получилась фрагментация
подумал что таким образом мы сможем быстро прыгать по памяти, но на самом деле, достаточно сохранять просто длину value для того, чтобы знать где находится следующее значение
а с этой фрагментацией, по идее, мы пока что только съедаем память

2023-10-10 00:27 UTC, stormrvge commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +            byte keySize = data.get(ValueLayout.JAVA_BYTE, pos++);
1 байт это же 256 значений, подумал, что ключ в 256 значений это нормально
условно, если длина ключа 253, тогда у нас там записано 11111101

возможно, и правда мало
но редко встречал, чтобы ключи были такие длинные, думал сэкономить память (мем про фрагментацию)

2023-10-10 00:41 UTC, stormrvge commented
а я могу пофиксить, либо просто ответить на вопросы и далее оценка?

2023-10-10 18:36 UTC, atimofeyev commented
У вас еще есть время поправить,  правками бал может быть чуть выше

2023-10-11 20:22 UTC, stormrvge commented
Код исправил

2023-10-17 21:07 UTC, atimofeyev requested changes

2023-10-17 21:07 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +        arena = Arena.ofConfined();
Не рабочий вариант в многопоточной среде

2023-10-17 21:12 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +        arena = Arena.ofConfined();
5 баллов

2023-10-17 21:12 UTC, atimofeyev approved these changes

2023-10-17 21:17 UTC, atimofeyev commented
Текущие замечания поправьте пожалуйста уже в след пул реквесте этапа 3, там будут тесты которые не пройдут в текущем решении

2023-10-17 21:22 UTC, merged

2023-10-17 21:23 UTC, stormrvge commented on src/main/java/ru/vk/itmo/svistukhinandrey/SSTable.java
> +        arena = Arena.ofConfined();
всё так плохо?