Новичков Андрей Юрьевич, М33321 ФИТиП, Persistent Dao
polis-vk/2023-nosql-lsm pull request #95
Opened 2023-10-03 11:48 UTC by croil

2023-10-15 21:13 UTC, ikriushenkov requested changes
В основном нужно выгрузку индексов в память. С ней 5/15

2023-10-15 21:13 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/novichkovandrew/PersistentDao.java
> +        }
Здесь происходит что-то странное. Непонятно, зачем сначала записывать всю информацию в файл, а потом сразу вычитывать из него, забывая, что он существует. Бин поиск нужно будет реализовать в следующем задании, поэтому здесь можно сделать без него, или без вычитывания обратно в память

2023-10-15 21:13 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/novichkovandrew/PersistentDao.java
> +        if (comparator.compare(sstKey, key) != 0) {
Для сравнения двух сегментов на равенство `compare` излишен. Достаточно лишь первого его сравнения, чтобы узнать, равны ли объекты

2023-10-15 23:12 UTC, croil commented on src/main/java/ru/vk/itmo/novichkovandrew/PersistentDao.java
> +public class PersistentDao extends InMemoryDao {
ImMemoryDao ничего не пишет на диск, там только in-memory операции же. Это же родитель. А вот PersistentDao пишет in-memory, а читает или in-memory или с диска.

2023-10-15 23:13 UTC, croil commented on src/main/java/ru/vk/itmo/novichkovandrew/PersistentDao.java
> +        }
Исправил в следующем дз

2023-10-15 23:14 UTC, croil commented on src/main/java/ru/vk/itmo/novichkovandrew/PersistentDao.java
> +                    indexFile.newLine();
Исправил в следующем дз

2023-10-15 23:15 UTC, croil commented on src/main/java/ru/vk/itmo/novichkovandrew/PersistentDao.java
> +        if (comparator.compare(sstKey, key) != 0) {
"Первого его сравнения" -- имеется в виду первого различающегося байта? Если да, то compare  так и работает, иначе не совсем понял

2023-10-18 21:00 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/novichkovandrew/PersistentDao.java
> +public class PersistentDao extends InMemoryDao {
Да, представьте, что вам приходит в функцию `void foo(InMemoryDao dao)` `PersistentDao`. Ожидаете ли вы по структуре класса и его названию, что он будет что-то читать с диска?

2023-10-18 21:02 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/novichkovandrew/PersistentDao.java
> +        if (comparator.compare(sstKey, key) != 0) {
Я имел ввиду, что вам нужно только узнать равны ли `MemorySegment`. `compare` же делает лишние действия в виде чтения различающегося байта и сравнения с размерами файлов

2023-10-18 21:35 UTC, ikriushenkov approved these changes
Все нужно было делать через `MemorySegment`. 10/15

2023-10-18 21:35 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/novichkovandrew/Utils.java
> +        ByteBuffer buffer = ByteBuffer.allocate(Long.BYTES);
В задании не планировалось использование `ByteBuffer`. Все должно было быть реализовано через сегменты

2023-10-22 12:18 UTC, merged