Трофимов Максим ИТМО ФИТиП бакалавр, stage 2
polis-vk/2023-nosql-lsm pull request #99
Opened 2023-10-03 20:23 UTC by trofik00777

2023-10-15 20:46 UTC, ikriushenkov requested changes
Обязательно нужно поправить на использование `FileChannel`. Пока 3/15 за старания

2023-10-15 20:46 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +    private SsTable ssTable;
`final`

2023-10-15 20:46 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        ArrayList<SsTable.Offset> offsets = new ArrayList<>();
Лучше использовать интерфейсы `List<SsTable.Offset>`

2023-10-15 20:46 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        try (FileOutputStream stream = new FileOutputStream(
В задании нужно было использовать `FileChannel`

2023-10-15 20:46 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +    private class SsTable {
Кажется, класс может быть `static`

2023-10-15 20:46 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        List<Offset> offsetsTable;
В этом классе потеряны все модификаторы доступа

2023-10-15 20:46 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +                data = channel.map(FileChannel.MapMode.READ_ONLY, 0, randomAccessFile.length(), Arena.global());
`Arena.global()` - плохо, так как участки, которые ей выделяются, никогда не освобождаются

2023-10-15 20:46 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +                if (COMPARE_SEGMENT.compare(currentKey, key) == 0) {
`compare` делает лишние действия, которые не нужны для того, чтобы сравнить на равенство два `MemorySegment`'а

2023-10-15 20:46 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        }
Копировать по одному байту долго и дорого. Посмотрите методы `MemorySegment`, там есть то, что вам нужно

2023-10-16 21:07 UTC, trofik00777 commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +    private SsTable ssTable;
fix

2023-10-16 21:07 UTC, trofik00777 commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        ArrayList<SsTable.Offset> offsets = new ArrayList<>();
fix

2023-10-16 21:07 UTC, trofik00777 commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        try (FileOutputStream stream = new FileOutputStream(
fix

2023-10-16 21:07 UTC, trofik00777 commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +    private class SsTable {
fix

2023-10-16 21:07 UTC, trofik00777 commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        List<Offset> offsetsTable;
fix

2023-10-16 21:08 UTC, trofik00777 commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +                data = channel.map(FileChannel.MapMode.READ_ONLY, 0, randomAccessFile.length(), Arena.global());
fix

2023-10-16 21:08 UTC, trofik00777 commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +                if (COMPARE_SEGMENT.compare(currentKey, key) == 0) {
Переписал на бинпоиск

2023-10-16 21:08 UTC, trofik00777 commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        }
fix

2023-10-18 20:58 UTC, ikriushenkov approved these changes
10/15

2023-10-18 20:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +            try (FileChannel fileChannelData = FileChannel.open(config.basePath().resolve(FILENAME + ".data"),
Странное решение, вы и здесь и в SsTable используете эти имена, причем каждый раз резолвите заново и вручную указываете расширения файлов

2023-10-18 20:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        SsTable(Path basePath, String filename) {
Модификаторы доступа все еще потеряны

2023-10-18 20:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +            Logger logger = Logger.getLogger(InMemoryDao.class.getName());
Если вы решили использовать логгер, то обычно его выделяют в отдельную статическую переменную, а не создают где-то локально в функции/конструкторе

2023-10-18 20:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +            }
Эти ошибки лучше пробрасывать пользователю, сигнатура функции специально изменилась, чтобы она могла бросать `IOException`

2023-10-18 20:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        private MemorySegment offsetsTable;
`final`

2023-10-18 20:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        static class Offset implements Serializable {
`implements Serializable` лишнее

2023-10-18 20:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +        }
После пробрасывания ошибки это не понадобится

2023-10-18 20:58 UTC, ikriushenkov commented on src/main/java/ru/vk/itmo/trofimovmaxim/InMemoryDao.java
> +            long val2Size = offsetsTable.get(ValueLayout.JAVA_LONG_UNALIGNED, offset + 3L * Long.BYTES);
Лишние чтения, они нужны только когда мы нашли нужный сегмент

2023-10-22 12:12 UTC, merged